// Simulating a database of popular songs with their keys and BPMs
// Expanded to ~100 songs for reference
const SONG_DATABASE = [
    { id: 1, title: "Bohemian Rhapsody", artist: "Queen", key: "Bb Major", bpm: 72, cover: "https://upload.wikimedia.org/wikipedia/en/9/9f/Bohemian_Rhapsody.png", genre: "Rock" },
    { id: 2, title: "Shape of You", artist: "Ed Sheeran", key: "C# Minor", bpm: 96, cover: "https://upload.wikimedia.org/wikipedia/en/b/b4/Shape_Of_You_%28Official_Single_Cover%29.png", genre: "Pop", chords: ['C#', 'F#', 'G#', 'A'] },
    { id: 3, title: "Blinding Lights", artist: "The Weeknd", key: "F Minor", bpm: 171, cover: "https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png", genre: "Pop", chords: ['Fm', 'Eb', 'Bb', 'Dm'] },
    { id: 4, title: "Someone Like You", artist: "Adele", key: "A Major", bpm: 67, cover: "https://upload.wikimedia.org/wikipedia/en/7/7a/Adele_-_Someone_Like_You.png", genre: "Pop", chords: ['A', 'E', 'F#', 'D'] },
    { id: 5, title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", key: "D Minor", bpm: 115, cover: "https://upload.wikimedia.org/wikipedia/en/a/a7/Mark_Ronson_-_Uptown_Funk_%28feat._Bruno_Mars%29_%28Official_Single_Cover%29.png", genre: "Pop" },
    { id: 6, title: "Hotel California", artist: "Eagles", key: "B Minor", bpm: 74, cover: "https://upload.wikimedia.org/wikipedia/en/4/49/Hotelcalifornia.jpg", genre: "Rock" },
    { id: 7, title: "Sweet Child O' Mine", artist: "Guns N' Roses", key: "Db Major", bpm: 125, cover: "https://upload.wikimedia.org/wikipedia/en/6/60/GunsnRosesAppetiteforDestruction.jpg", genre: "Rock", chords: ['D', 'C', 'G', 'A'] },
    { id: 8, title: "Billie Jean", artist: "Michael Jackson", key: "F# Minor", bpm: 117, cover: "https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png", genre: "Pop" },
    { id: 9, title: "Smells Like Teen Spirit", artist: "Nirvana", key: "F Minor", bpm: 116, cover: "https://upload.wikimedia.org/wikipedia/en/3/3c/Smells_Like_Teen_Spirit.jpg", genre: "Rock" },
    { id: 10, title: "Imagine", artist: "John Lennon", key: "C Major", bpm: 76, cover: "https://upload.wikimedia.org/wikipedia/en/6/69/ImagineCover.jpg", genre: "Rock", chords: ['C', 'F', 'Am', 'Dm'] },
    { id: 11, title: "Hallelujah", artist: "Jeff Buckley", key: "C Major", bpm: 48, cover: "https://upload.wikimedia.org/wikipedia/en/7/7e/Jeff_Buckley_-_Grace.jpg", genre: "Rock" },
    { id: 12, title: "Hey Jude", artist: "The Beatles", key: "F Major", bpm: 74, cover: "https://upload.wikimedia.org/wikipedia/en/4/4d/The_Beatles_-_Hey_Jude.jpg", genre: "Rock", chords: ['F', 'C', 'Bb', 'F'] },
    { id: 13, title: "Rolling in the Deep", artist: "Adele", key: "C Minor", bpm: 105, cover: "https://upload.wikimedia.org/wikipedia/en/7/74/Adele_-_Rolling_in_the_Deep.png", genre: "Pop", chords: ['C', 'Gm', 'Bb', 'F'] },
    { id: 14, title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", key: "B Minor", bpm: 89, cover: "https://upload.wikimedia.org/wikipedia/en/c/c8/Luis_Fonsi_Feat._Daddy_Yankee_-_Despacito_%28Official_Single_Cover%29.png", genre: "Pop" },
    { id: 15, title: "Levitating", artist: "Dua Lipa", key: "B Minor", bpm: 103, cover: "https://upload.wikimedia.org/wikipedia/en/f/f5/Dua_Lipa_-_Levitating.png", genre: "Pop" },
    { id: 16, title: "Stay", artist: "The Kid LAROI & Justin Bieber", key: "C# Major", bpm: 170, cover: "https://upload.wikimedia.org/wikipedia/en/0/0c/The_Kid_Laroi_and_Justin_Bieber_-_Stay.png", genre: "Pop" },
    { id: 17, title: "As It Was", artist: "Harry Styles", key: "A Minor", bpm: 174, cover: "https://upload.wikimedia.org/wikipedia/en/b/b1/Harry_Styles_-_As_It_Was.png", genre: "Pop", chords: ['Am', 'F', 'C', 'G'] },
    { id: 18, title: "Flowers", artist: "Miley Cyrus", key: "A Minor", bpm: 118, cover: "https://upload.wikimedia.org/wikipedia/en/a/a3/Miley_Cyrus_-_Flowers.png", genre: "Pop" },
    { id: 19, title: "Drivers License", artist: "Olivia Rodrigo", key: "Bb Major", bpm: 144, cover: "https://upload.wikimedia.org/wikipedia/en/0/09/Olivia_Rodrigo_-_Drivers_License.png", genre: "Pop" },
    { id: 20, title: "Bad Guy", artist: "Billie Eilish", key: "G Minor", bpm: 135, cover: "https://upload.wikimedia.org/wikipedia/en/3/33/Billie_Eilish_-_Bad_Guy.png", genre: "Pop" },
    { id: 21, title: "Watermelon Sugar", artist: "Harry Styles", key: "D Minor", bpm: 95, cover: "https://upload.wikimedia.org/wikipedia/en/b/b1/Harry_Styles_-_Fine_Line.png", genre: "Pop" },
    { id: 22, title: "Don't Start Now", artist: "Dua Lipa", key: "B Minor", bpm: 124, cover: "https://upload.wikimedia.org/wikipedia/en/1/1c/Dua_Lipa_-_Don%27t_Start_Now.png", genre: "Pop" },
    { id: 23, title: "Save Your Tears", artist: "The Weeknd", key: "C Major", bpm: 118, cover: "https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png", genre: "Pop" },
    { id: 24, title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", key: "G# Minor", bpm: 179, cover: "https://upload.wikimedia.org/wikipedia/en/6/63/Lil_Nas_X_-_Montero_%28Call_Me_by_Your_Name%29.png", genre: "Hip-Hop" },
    { id: 25, title: "Peaches", artist: "Justin Bieber", key: "C Major", bpm: 90, cover: "https://upload.wikimedia.org/wikipedia/en/0/00/Justin_Bieber_-_Justice.png", genre: "Pop" },
    { id: 26, title: "Good 4 U", artist: "Olivia Rodrigo", key: "F# Minor", bpm: 167, cover: "https://upload.wikimedia.org/wikipedia/en/6/69/Olivia_Rodrigo_-_Sour.png", genre: "Pop" },
    { id: 27, title: "Kiss Me More", artist: "Doja Cat ft. SZA", key: "G# Major", bpm: 111, cover: "https://upload.wikimedia.org/wikipedia/en/8/87/Doja_Cat_-_Kiss_Me_More.png", genre: "R&B" },
    { id: 28, title: "Industry Baby", artist: "Lil Nas X", key: "D# Minor", bpm: 150, cover: "https://upload.wikimedia.org/wikipedia/en/6/63/Lil_Nas_X_-_Montero_%28Call_Me_by_Your_Name%29.png", genre: "Hip-Hop" },
    { id: 29, title: "Heat Waves", artist: "Glass Animals", key: "B Major", bpm: 81, cover: "https://upload.wikimedia.org/wikipedia/en/b/b0/Glass_Animals_-_Dreamland.png", genre: "Pop" },
    { id: 30, title: "Shivers", artist: "Ed Sheeran", key: "D Major", bpm: 141, cover: "https://upload.wikimedia.org/wikipedia/en/4/4e/Ed_Sheeran_-_Equals.png", genre: "Pop" },
    { id: 31, title: "Cold Heart", artist: "Elton John & Dua Lipa", key: "C# Minor", bpm: 116, genre: "Pop" },
    { id: 32, title: "Easy On Me", artist: "Adele", key: "F Major", bpm: 142, genre: "Pop" },
    { id: 33, title: "ABCDEFU", artist: "GAYLE", key: "E Major", bpm: 122, genre: "Pop" },
    { id: 34, title: "Ghost", artist: "Justin Bieber", key: "B Minor", bpm: 154, genre: "Pop" },
    { id: 35, title: "Enemy", artist: "Imagine Dragons", key: "B Minor", bpm: 77, genre: "Rock" },
    { id: 36, title: "Running Up That Hill", artist: "Kate Bush", key: "C Minor", bpm: 108, genre: "Pop" },
    { id: 37, title: "Anti-Hero", artist: "Taylor Swift", key: "B Major", bpm: 97, genre: "Pop" },
    { id: 38, title: "Unholy", artist: "Sam Smith & Kim Petras", key: "C# Major", bpm: 131, genre: "Pop" },
    { id: 39, title: "Kill Bill", artist: "SZA", key: "Bb Major", bpm: 89, genre: "R&B" },
    { id: 40, title: "Creepin'", artist: "Metro Boomin", key: "C# Minor", bpm: 98, genre: "Hip-Hop" },
    { id: 96, title: "Since U Been Gone", artist: "Kelly Clarkson", key: "G Major", bpm: 131, genre: "Pop" },
    { id: 97, title: "Shake It Off", artist: "Taylor Swift", key: "G Major", bpm: 160, genre: "Pop" },
    { id: 98, title: "Crazy", artist: "Gnarls Barkley", key: "C Minor", bpm: 112 },
    { id: 99, title: "Promiscuous", artist: "Nelly Furtado", key: "Bb Minor", bpm: 114 },
    { id: 100, title: "SexyBack", artist: "Justin Timberlake", key: "C Major", bpm: 117 },
    { id: 101, title: "Don't Stop Believin'", artist: "Journey", key: "E Major", bpm: 119 },
    { id: 102, title: "Livin' on a Prayer", artist: "Bon Jovi", key: "E Minor", bpm: 123 },
    { id: 103, title: "Africa", artist: "Toto", key: "A Major", bpm: 93 },
    { id: 104, title: "Take on Me", artist: "a-ha", key: "A Major", bpm: 169 },
    { id: 105, title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", key: "C Minor", bpm: 125 },
    { id: 106, title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", key: "F# Major", bpm: 120 },
    { id: 107, title: "I Will Survive", artist: "Gloria Gaynor", key: "A Minor", bpm: 116 },
    { id: 108, title: "Eye of the Tiger", artist: "Survivor", key: "C Minor", bpm: 109 },
    { id: 109, title: "Beat It", artist: "Michael Jackson", key: "Eb Minor", bpm: 139 },
    { id: 110, title: "Under Pressure", artist: "Queen & David Bowie", key: "D Major", bpm: 113 },
    { id: 111, title: "Another One Bites the Dust", artist: "Queen", key: "E Minor", bpm: 110 },
    { id: 112, title: "We Will Rock You", artist: "Queen", key: "E Minor", bpm: 81 },
    { id: 113, title: "Summer of '69", artist: "Bryan Adams", key: "D Major", bpm: 139 },
    { id: 114, title: "Jump", artist: "Van Halen", key: "C Major", bpm: 130 },
    { id: 115, title: "Pour Some Sugar on Me", artist: "Def Leppard", key: "C# Minor", bpm: 85 },
    { id: 116, title: "Welcome to the Jungle", artist: "Guns N' Roses", key: "Eb Minor", bpm: 123 },
    { id: 117, title: "Paradise City", artist: "Guns N' Roses", key: "G Major", bpm: 100 },
    { id: 118, title: "November Rain", artist: "Guns N' Roses", key: "B Major", bpm: 79 },
    { id: 119, title: "Enter Sandman", artist: "Metallica", key: "F# Minor", bpm: 123 },
    { id: 120, title: "Nothing Else Matters", artist: "Metallica", key: "E Minor", bpm: 142 },
    { id: 121, title: "Wonderwall", artist: "Oasis", key: "F# Minor", bpm: 87 },
    { id: 122, title: "Don't Look Back in Anger", artist: "Oasis", key: "C Major", bpm: 163 },
    { id: 123, title: "Bitter Sweet Symphony", artist: "The Verve", key: "E Major", bpm: 84 },
    { id: 124, title: "Creep", artist: "Radiohead", key: "G Major", bpm: 92 },
    { id: 125, title: "No Surprises", artist: "Radiohead", key: "F Major", bpm: 76 },
    { id: 126, title: "Karma Police", artist: "Radiohead", key: "A Minor", bpm: 75 },
    { id: 127, title: "Californication", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 96 },
    { id: 128, title: "Under the Bridge", artist: "Red Hot Chili Peppers", key: "E Major", bpm: 85 },
    { id: 129, title: "Otherside", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 123 },
    { id: 130, title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", key: "G# Minor", bpm: 105 },
    { id: 131, title: "Can't Stop", artist: "Red Hot Chili Peppers", key: "E Minor", bpm: 91 },
    { id: 132, title: "Dani California", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 96 },
    { id: 133, title: "By the Way", artist: "Red Hot Chili Peppers", key: "F Major", bpm: 122 },
    { id: 134, title: "Scar Tissue", artist: "Red Hot Chili Peppers", key: "F Major", bpm: 89 },
    { id: 135, title: "Give It Away", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 92 },
    { id: 136, title: "Every Breath You Take", artist: "The Police", key: "Ab Major", bpm: 117 },
    { id: 137, title: "Roxanne", artist: "The Police", key: "G Minor", bpm: 134 },
    { id: 138, title: "Message in a Bottle", artist: "The Police", key: "C# Minor", bpm: 150 },
    { id: 139, title: "Die With a Smile", artist: "Lady Gaga & Bruno Mars", key: "F Major", bpm: 124 },
    { id: 140, title: "Espresso", artist: "Sabrina Carpenter", key: "F# Minor", bpm: 104 },
    { id: 141, title: "A Bar Song (Tipsy)", artist: "Shaboozey", key: "A Major", bpm: 140 },
    { id: 142, title: "Beautiful Things", artist: "Benson Boone", key: "Eb Major", bpm: 120 },
    { id: 143, title: "Cruel Summer", artist: "Taylor Swift", key: "A Major", bpm: 170 },
    { id: 144, title: "Paint The Town Red", artist: "Doja Cat", key: "Eb Minor", bpm: 110 },
    { id: 145, title: "Lovin On Me", artist: "Jack Harlow", key: "F# Minor", bpm: 83 },
    { id: 146, title: "Agora Hills", artist: "Doja Cat", key: "Bb Major", bpm: 140 },
    { id: 147, title: "What Was I Made For?", artist: "Billie Eilish", key: "C Major", bpm: 104 },
    { id: 148, title: "Vampire", artist: "Olivia Rodrigo", key: "F Major", bpm: 134 },
    { id: 149, title: "Snooze", artist: "SZA", key: "C# Minor", bpm: 102 },
    { id: 150, title: "Daylight", artist: "David Kushner", key: "G Minor", bpm: 80 },
    { id: 151, title: "Please Please Please", artist: "Sabrina Carpenter", key: "C# Minor", bpm: 106 },
    { id: 152, title: "Taste", artist: "Sabrina Carpenter", key: "A Minor", bpm: 107 },
    { id: 153, title: "Birds of a Feather", artist: "Billie Eilish", key: "Bb Major", bpm: 104 },
    { id: 154, title: "Good Luck, Babe!", artist: "Chappell Roan", key: "C Major", bpm: 119 },
    { id: 155, title: "Too Sweet", artist: "Hozier", key: "G Major", bpm: 142 },
    { id: 156, title: "Fortnight", artist: "Taylor Swift ft. Post Malone", key: "Eb Major", bpm: 109 },
    { id: 157, title: "Not Like Us", artist: "Kendrick Lamar", key: "A Minor", bpm: 98 },
    { id: 158, title: "TEXAS HOLD 'EM", artist: "Beyoncé", key: "Bb Major", bpm: 97 },
    { id: 159, title: "I Had Some Help", artist: "Post Malone ft. Morgan Wallen", key: "A Major", bpm: 80 },
    { id: 160, title: "Stick Season", artist: "Noah Kahan", key: "C Major", bpm: 142 },
    { id: 161, title: "Dial Drunk", artist: "Noah Kahan", key: "F Major", bpm: 94 },
    { id: 162, title: "Lose Control", artist: "Teddy Swims", key: "F# Minor", bpm: 140 },
    { id: 163, title: "I Remember Everything", artist: "Zach Bryan ft. Kacey Musgraves", key: "D Major", bpm: 138 },
    { id: 164, title: "Greedy", artist: "Tate McRae", key: "C# Minor", bpm: 122 },
    { id: 165, title: "Exes", artist: "Tate McRae", key: "A Minor", bpm: 108 },
    { id: 166, title: "you're gonna go far", artist: "Noah Kahan", key: "G Major", bpm: 116 },
    { id: 167, title: "Paint the Town Red", artist: "Doja Cat", key: "Eb Minor", bpm: 110 },
    { id: 168, title: "Strangers", artist: "Kenya Grace", key: "F# Minor", bpm: 128 },
    { id: 169, title: "Karma", artist: "Taylor Swift", key: "E Major", bpm: 90 },
    { id: 170, title: "Lavender Haze", artist: "Taylor Swift", key: "F# Major", bpm: 97 },
    { id: 171, title: "Nonsense", artist: "Sabrina Carpenter", key: "Eb Major", bpm: 120 },
    { id: 172, title: "Feather", artist: "Sabrina Carpenter", key: "C# Minor", bpm: 102 },
    { id: 173, title: "Lover", artist: "Taylor Swift", key: "C Major", bpm: 68 },
    { id: 174, title: "Cardigan", artist: "Taylor Swift", key: "Eb Major", bpm: 130 },
    { id: 175, title: "Willow", artist: "Taylor Swift", key: "F Major", bpm: 100 },
    { id: 176, title: "august", artist: "Taylor Swift", key: "Bb Major", bpm: 88 },
    { id: 177, title: "The 1", artist: "Taylor Swift", key: "G Major", bpm: 84 },
    { id: 178, title: "exile", artist: "Taylor Swift ft. Bon Iver", key: "Bb Major", bpm: 94 },
    { id: 179, title: "my tears ricochet", artist: "Taylor Swift", key: "Ab Major", bpm: 102 },
    { id: 180, title: "mirrorball", artist: "Taylor Swift", key: "Bb Major", bpm: 109 },
    { id: 181, title: "betty", artist: "Taylor Swift", key: "Ab Major", bpm: 97 },
    { id: 182, title: "peace", artist: "Taylor Swift", key: "Eb Major", bpm: 90 },
    { id: 183, title: "hoax", artist: "Taylor Swift", key: "Ab Major", bpm: 76 },
    { id: 184, title: "Carolina", artist: "Taylor Swift", key: "G Major", bpm: 128 },
    { id: 185, title: "Snow On The Beach", artist: "Taylor Swift ft. Lana Del Rey", key: "Eb Major", bpm: 101 },
    { id: 186, title: "Bejeweled", artist: "Taylor Swift", key: "C Major", bpm: 105 },
    { id: 187, title: "Mastermind", artist: "Taylor Swift", key: "F# Major", bpm: 106 },
    { id: 188, title: "Vigilante Shit", artist: "Taylor Swift", key: "C Minor", bpm: 90 },
    { id: 189, title: "Labyrinth", artist: "Taylor Swift", key: "Bb Major", bpm: 86 },
    { id: 190, title: "Sweet Nothing", artist: "Taylor Swift", key: "C Major", bpm: 105 },
    { id: 191, title: "Maroon", artist: "Taylor Swift", key: "C Major", bpm: 83 },
    { id: 192, title: "Question...?", artist: "Taylor Swift", key: "A Major", bpm: 99 },
    { id: 193, title: "Midnight Rain", artist: "Taylor Swift", key: "Db Major", bpm: 90 },
    { id: 194, title: "You're On Your Own, Kid", artist: "Taylor Swift", key: "A Major", bpm: 107 },
    { id: 195, title: "Is It Over Now?", artist: "Taylor Swift", key: "A Major", bpm: 137 },
    { id: 196, title: "Now That We Don't Talk", artist: "Taylor Swift", key: "F# Major", bpm: 102 },
    { id: 197, title: "Suburban Legends", artist: "Taylor Swift", key: "D Major", bpm: 107 },
    { id: 198, title: "Slut!", artist: "Taylor Swift", key: "Gb Major", bpm: 88 },
    { id: 199, title: "Say Don't Go", artist: "Taylor Swift", key: "C Major", bpm: 124 },
    { id: 200, title: "Timeless", artist: "Taylor Swift", key: "D Major", bpm: 100 },

    // K-POP SECTION - Top 100 K-pop Songs
    { id: 201, title: "Dynamite", artist: "BTS", key: "C# Minor", bpm: 114, genre: "K-pop" },
    { id: 202, title: "Butter", artist: "BTS", key: "A Major", bpm: 110, genre: "K-pop" },
    { id: 203, title: "Permission to Dance", artist: "BTS", key: "C# Major", bpm: 125, genre: "K-pop" },
    { id: 204, title: "Boy With Luv", artist: "BTS ft. Halsey", key: "E Major", bpm: 120, genre: "K-pop" },
    { id: 205, title: "DNA", artist: "BTS", key: "Eb Minor", bpm: 130, genre: "K-pop" },
    { id: 206, title: "IDOL", artist: "BTS", key: "F# Minor", bpm: 150, genre: "K-pop" },
    { id: 207, title: "MIC Drop", artist: "BTS", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 208, title: "Fake Love", artist: "BTS", key: "C# Minor", bpm: 140, genre: "K-pop" },
    { id: 209, title: "Blood Sweat & Tears", artist: "BTS", key: "D Minor", bpm: 120, genre: "K-pop" },
    { id: 210, title: "Spring Day", artist: "BTS", key: "Ab Major", bpm: 120, genre: "K-pop" },
    { id: 211, title: "Life Goes On", artist: "BTS", key: "Eb Major", bpm: 72, genre: "K-pop" },
    { id: 212, title: "ON", artist: "BTS", key: "C Minor", bpm: 144, genre: "K-pop" },
    { id: 213, title: "Black Swan", artist: "BTS", key: "E Minor", bpm: 104, genre: "K-pop" },
    { id: 214, title: "Yet To Come", artist: "BTS", key: "F Major", bpm: 92, genre: "K-pop" },
    { id: 215, title: "Run BTS", artist: "BTS", key: "G Minor", bpm: 130, genre: "K-pop" },

    { id: 216, title: "DDU-DU DDU-DU", artist: "BLACKPINK", key: "G Minor", bpm: 145, genre: "K-pop" },
    { id: 217, title: "Kill This Love", artist: "BLACKPINK", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 218, title: "How You Like That", artist: "BLACKPINK", key: "D Minor", bpm: 132, genre: "K-pop" },
    { id: 219, title: "Pink Venom", artist: "BLACKPINK", key: "F# Minor", bpm: 90, genre: "K-pop" },
    { id: 220, title: "Shut Down", artist: "BLACKPINK", key: "F Minor", bpm: 125, genre: "K-pop" },
    { id: 221, title: "BOOMBAYAH", artist: "BLACKPINK", key: "Bb Minor", bpm: 130, genre: "K-pop" },
    { id: 222, title: "As If It's Your Last", artist: "BLACKPINK", key: "F# Minor", bpm: 132, genre: "K-pop" },
    { id: 223, title: "Lovesick Girls", artist: "BLACKPINK", key: "Bb Minor", bpm: 130, genre: "K-pop" },
    { id: 224, title: "Playing With Fire", artist: "BLACKPINK", key: "F# Minor", bpm: 120, genre: "K-pop" },
    { id: 225, title: "Forever Young", artist: "BLACKPINK", key: "C# Minor", bpm: 132, genre: "K-pop" },

    { id: 226, title: "OMG", artist: "NewJeans", key: "F# Minor", bpm: 125, genre: "K-pop" },
    { id: 227, title: "Ditto", artist: "NewJeans", key: "A Major", bpm: 120, genre: "K-pop" },
    { id: 228, title: "Attention", artist: "NewJeans", key: "C# Minor", bpm: 125, genre: "K-pop" },
    { id: 229, title: "Hype Boy", artist: "NewJeans", key: "Bb Minor", bpm: 122, genre: "K-pop" },
    { id: 230, title: "Super Shy", artist: "NewJeans", key: "F Major", bpm: 125, genre: "K-pop" },
    { id: 231, title: "ETA", artist: "NewJeans", key: "E Minor", bpm: 138, genre: "K-pop" },
    { id: 232, title: "Cool With You", artist: "NewJeans", key: "G Major", bpm: 115, genre: "K-pop" },

    { id: 233, title: "God's Menu", artist: "Stray Kids", key: "F Minor", bpm: 180, genre: "K-pop" },
    { id: 234, title: "MANIAC", artist: "Stray Kids", key: "G Minor", bpm: 140, genre: "K-pop" },
    { id: 235, title: "Back Door", artist: "Stray Kids", key: "Eb Minor", bpm: 140, genre: "K-pop" },
    { id: 236, title: "Thunderous", artist: "Stray Kids", key: "F# Minor", bpm: 150, genre: "K-pop" },
    { id: 237, title: "S-Class", artist: "Stray Kids", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 238, title: "LALALALA", artist: "Stray Kids", key: "F Minor", bpm: 145, genre: "K-pop" },
    { id: 239, title: "Case 143", artist: "Stray Kids", key: "C# Minor", bpm: 138, genre: "K-pop" },

    { id: 240, title: "FANCY", artist: "TWICE", key: "C# Minor", bpm: 132, genre: "K-pop" },
    { id: 241, title: "Feel Special", artist: "TWICE", key: "Bb Minor", bpm: 120, genre: "K-pop" },
    { id: 242, title: "TT", artist: "TWICE", key: "C# Minor", bpm: 120, genre: "K-pop" },
    { id: 243, title: "Cheer Up", artist: "TWICE", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 244, title: "What is Love?", artist: "TWICE", key: "Eb Minor", bpm: 128, genre: "K-pop" },
    { id: 245, title: "I CAN'T STOP ME", artist: "TWICE", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 246, title: "Alcohol-Free", artist: "TWICE", key: "G Major", bpm: 120, genre: "K-pop" },
    { id: 247, title: "The Feels", artist: "TWICE", key: "F# Major", bpm: 120, genre: "K-pop" },
    { id: 248, title: "Talk that Talk", artist: "TWICE", key: "Bb Minor", bpm: 125, genre: "K-pop" },
    { id: 249, title: "SET ME FREE", artist: "TWICE", key: "D Minor", bpm: 130, genre: "K-pop" },

    { id: 250, title: "Cupid", artist: "FIFTY FIFTY", key: "F# Major", bpm: 125, genre: "K-pop" },
    { id: 251, title: "Perfect Night", artist: "LE SSERAFIM", key: "C# Minor", bpm: 128, genre: "K-pop" },
    { id: 252, title: "ANTIFRAGILE", artist: "LE SSERAFIM", key: "F Minor", bpm: 125, genre: "K-pop" },
    { id: 253, title: "UNFORGIVEN", artist: "LE SSERAFIM", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 254, title: "Eve, Psyche & The Bluebeard's wife", artist: "LE SSERAFIM", key: "Bb Minor", bpm: 135, genre: "K-pop" },

    { id: 255, title: "Queencard", artist: "(G)I-DLE", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 256, title: "Tomboy", artist: "(G)I-DLE", key: "E Minor", bpm: 130, genre: "K-pop" },
    { id: 257, title: "Nxde", artist: "(G)I-DLE", key: "G Minor", bpm: 125, genre: "K-pop" },
    { id: 258, title: "LATATA", artist: "(G)I-DLE", key: "F# Minor", bpm: 120, genre: "K-pop" },
    { id: 259, title: "Oh my god", artist: "(G)I-DLE", key: "D Minor", bpm: 128, genre: "K-pop" },

    { id: 260, title: "Psycho", artist: "Red Velvet", key: "Bb Minor", bpm: 138, genre: "K-pop" },
    { id: 261, title: "Bad Boy", artist: "Red Velvet", key: "F# Minor", bpm: 92, genre: "K-pop" },
    { id: 262, title: "Red Flavor", artist: "Red Velvet", key: "Bb Major", bpm: 120, genre: "K-pop" },
    { id: 263, title: "Peek-A-Boo", artist: "Red Velvet", key: "F Minor", bpm: 120, genre: "K-pop" },
    { id: 264, title: "Russian Roulette", artist: "Red Velvet", key: "Eb Major", bpm: 132, genre: "K-pop" },
    { id: 265, title: "Feel My Rhythm", artist: "Red Velvet", key: "C Major", bpm: 120, genre: "K-pop" },

    { id: 266, title: "Love Dive", artist: "IVE", key: "F# Minor", bpm: 125, genre: "K-pop" },
    { id: 267, title: "After LIKE", artist: "IVE", key: "C# Minor", bpm: 128, genre: "K-pop" },
    { id: 268, title: "ELEVEN", artist: "IVE", key: "Bb Minor", bpm: 125, genre: "K-pop" },
    { id: 269, title: "Kitsch", artist: "IVE", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 270, title: "I AM", artist: "IVE", key: "F Minor", bpm: 128, genre: "K-pop" },

    { id: 271, title: "Magnetic", artist: "ILLIT", key: "E Major", bpm: 122, genre: "K-pop" },
    { id: 272, title: "Supernova", artist: "aespa", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 273, title: "Next Level", artist: "aespa", key: "F# Minor", bpm: 130, genre: "K-pop" },
    { id: 274, title: "Savage", artist: "aespa", key: "G Minor", bpm: 150, genre: "K-pop" },
    { id: 275, title: "Black Mamba", artist: "aespa", key: "F# Minor", bpm: 130, genre: "K-pop" },
    { id: 276, title: "Spicy", artist: "aespa", key: "Bb Minor", bpm: 128, genre: "K-pop" },
    { id: 277, title: "Drama", artist: "aespa", key: "E Minor", bpm: 125, genre: "K-pop" },

    { id: 278, title: "Gangnam Style", artist: "PSY", key: "C# Minor", bpm: 132, genre: "K-pop" },
    { id: 279, title: "Gentleman", artist: "PSY", key: "G Minor", bpm: 132, genre: "K-pop" },

    { id: 280, title: "MONEY", artist: "LISA", key: "F# Minor", bpm: 140, genre: "K-pop" },
    { id: 281, title: "LALISA", artist: "LISA", key: "Bb Minor", bpm: 130, genre: "K-pop" },
    { id: 282, title: "On The Ground", artist: "ROSÉ", key: "C# Minor", bpm: 70, genre: "K-pop" },
    { id: 283, title: "SOLO", artist: "JENNIE", key: "G Minor", bpm: 132, genre: "K-pop" },

    { id: 284, title: "Seven", artist: "Jungkook ft. Latto", key: "Bb Major", bpm: 125, genre: "K-pop" },
    { id: 285, title: "3D", artist: "Jungkook ft. Jack Harlow", key: "F# Minor", bpm: 144, genre: "K-pop" },
    { id: 286, title: "Left and Right", artist: "Charlie Puth ft. Jungkook", key: "D Major", bpm: 125, genre: "K-pop" },
    { id: 287, title: "Like Crazy", artist: "Jimin", key: "F# Minor", bpm: 125, genre: "K-pop" },
    { id: 288, title: "Set Me Free Pt.2", artist: "Jimin", key: "G Minor", bpm: 130, genre: "K-pop" },

    { id: 289, title: "Candy", artist: "NCT DREAM", key: "F# Major", bpm: 128, genre: "K-pop" },
    { id: 290, title: "Hot Sauce", artist: "NCT DREAM", key: "Bb Minor", bpm: 128, genre: "K-pop" },
    { id: 291, title: "Kick It", artist: "NCT 127", key: "F Minor", bpm: 130, genre: "K-pop" },
    { id: 292, title: "Sticker", artist: "NCT 127", key: "G Minor", bpm: 128, genre: "K-pop" },

    { id: 293, title: "Growl", artist: "EXO", key: "Bb Minor", bpm: 120, genre: "K-pop" },
    { id: 294, title: "Love Shot", artist: "EXO", key: "F# Minor", bpm: 95, genre: "K-pop" },
    { id: 295, title: "Monster", artist: "EXO", key: "C# Minor", bpm: 105, genre: "K-pop" },
    { id: 296, title: "Call Me Baby", artist: "EXO", key: "G Minor", bpm: 128, genre: "K-pop" },

    { id: 297, title: "Very Nice", artist: "SEVENTEEN", key: "F# Major", bpm: 128, genre: "K-pop" },
    { id: 298, title: "Don't Wanna Cry", artist: "SEVENTEEN", key: "Bb Minor", bpm: 120, genre: "K-pop" },
    { id: 299, title: "Super", artist: "SEVENTEEN", key: "C# Minor", bpm: 130, genre: "K-pop" },
    { id: 300, title: "HOT", artist: "SEVENTEEN", key: "F Minor", bpm: 125, genre: "K-pop" },

    // HIP-HOP SECTION - Top 100 Hip-Hop Songs
    { id: 301, title: "Not Like Us", artist: "Kendrick Lamar", key: "A Minor", bpm: 101, genre: "Hip-Hop" },
    { id: 302, title: "Like That", artist: "Future, Metro Boomin, Kendrick Lamar", key: "F Minor", bpm: 124, genre: "Hip-Hop" },
    { id: 303, title: "FE!N", artist: "Travis Scott ft. Playboi Carti", key: "F# Minor", bpm: 148, genre: "Hip-Hop" },
    { id: 304, title: "Carnival", artist: "Kanye West & Ty Dolla $ign", key: "G# Minor", bpm: 148, genre: "Hip-Hop" },
    { id: 305, title: "Lovin On Me", artist: "Jack Harlow", key: "F# Minor", bpm: 105, genre: "Hip-Hop" },
    { id: 306, title: "First Person Shooter", artist: "Drake ft. J. Cole", key: "F# Minor", bpm: 164, genre: "Hip-Hop" },
    { id: 307, title: "Rich Baby Daddy", artist: "Drake ft. Sexyy Red & SZA", key: "F Major", bpm: 146, genre: "Hip-Hop" },
    { id: 308, title: "Surround Sound", artist: "JID ft. 21 Savage", key: "G Minor", bpm: 152, genre: "Hip-Hop" },
    { id: 309, title: "Redrum", artist: "21 Savage", key: "C# Minor", bpm: 172, genre: "Hip-Hop" },
    { id: 310, title: "Agora Hills", artist: "Doja Cat", key: "Ab Major", bpm: 123, genre: "Hip-Hop" },
    { id: 311, title: "Paint The Town Red", artist: "Doja Cat", key: "C# Minor", bpm: 100, genre: "Hip-Hop" },
    { id: 312, title: "Fukumean", artist: "Gunna", key: "F Minor", bpm: 130, genre: "Hip-Hop" },
    { id: 313, title: "I Know ?", artist: "Travis Scott", key: "G# Minor", bpm: 118, genre: "Hip-Hop" },
    { id: 314, title: "Meltdown", artist: "Travis Scott ft. Drake", key: "F# Minor", bpm: 114, genre: "Hip-Hop" },
    { id: 315, title: "Trance", artist: "Metro Boomin, Travis Scott, Young Thug", key: "C Minor", bpm: 121, genre: "Hip-Hop" },
    { id: 316, title: "Superhero (Heroes & Villains)", artist: "Metro Boomin, Future, Chris Brown", key: "F Minor", bpm: 117, genre: "Hip-Hop" },
    { id: 317, title: "Rich Flex", artist: "Drake & 21 Savage", key: "B Minor", bpm: 147, genre: "Hip-Hop" },
    { id: 318, title: "Spin Bout U", artist: "Drake & 21 Savage", key: "F# Minor", bpm: 130, genre: "Hip-Hop" },
    { id: 319, title: "Wait For U", artist: "Future ft. Drake & Tems", key: "C# Minor", bpm: 83, genre: "Hip-Hop" },
    { id: 320, title: "Jimmy Cooks", artist: "Drake ft. 21 Savage", key: "C Minor", bpm: 166, genre: "Hip-Hop" },
    { id: 321, title: "First Class", artist: "Jack Harlow", key: "F Minor", bpm: 107, genre: "Hip-Hop" },
    { id: 322, title: "Staying Alive", artist: "DJ Khaled ft. Drake & Lil Baby", key: "F# Minor", bpm: 130, genre: "Hip-Hop" },
    { id: 323, title: "Sticky", artist: "Drake", key: "D Major", bpm: 137, genre: "Hip-Hop" },
    { id: 324, title: "Mockingbird", artist: "Eminem", key: "E Minor", bpm: 84, genre: "Hip-Hop" },
    { id: 325, title: "Without Me", artist: "Eminem", key: "E Minor", bpm: 112, genre: "Hip-Hop" },
    { id: 326, title: "The Real Slim Shady", artist: "Eminem", key: "C Minor", bpm: 104, genre: "Hip-Hop" },
    { id: 327, title: "Lose Yourself", artist: "Eminem", key: "D Minor", bpm: 171, genre: "Hip-Hop" },
    { id: 328, title: "God's Plan", artist: "Drake", key: "E Minor", bpm: 77, genre: "Hip-Hop" },
    { id: 329, title: "One Dance", artist: "Drake", key: "Bb Minor", bpm: 104, genre: "Hip-Hop" },
    { id: 330, title: "In My Feelings", artist: "Drake", key: "G# Minor", bpm: 91, genre: "Hip-Hop" },
    { id: 331, title: "Hotline Bling", artist: "Drake", key: "D Minor", bpm: 135, genre: "Hip-Hop" },
    { id: 332, title: "HUMBLE.", artist: "Kendrick Lamar", key: "Ab Minor", bpm: 150, genre: "Hip-Hop" },
    { id: 333, title: "Money Trees", artist: "Kendrick Lamar", key: "Bb Minor", bpm: 72, genre: "Hip-Hop" },
    { id: 334, title: "Swimming Pools (Drank)", artist: "Kendrick Lamar", key: "Ab Minor", bpm: 74, genre: "Hip-Hop" },
    { id: 335, title: "Alright", artist: "Kendrick Lamar", key: "G Minor", bpm: 110, genre: "Hip-Hop" },
    { id: 336, title: "DNA.", artist: "Kendrick Lamar", key: "E Minor", bpm: 140, genre: "Hip-Hop" },
    { id: 337, title: "Sicko Mode", artist: "Travis Scott", key: "Bb Major", bpm: 155, genre: "Hip-Hop" },
    { id: 338, title: "Goosebumps", artist: "Travis Scott", key: "G# Minor", bpm: 130, genre: "Hip-Hop" },
    { id: 339, title: "Highest in the Room", artist: "Travis Scott", key: "D Minor", bpm: 76, genre: "Hip-Hop" },
    { id: 340, title: "Butterfly Effect", artist: "Travis Scott", key: "F# Major", bpm: 141, genre: "Hip-Hop" },
    { id: 341, title: "Lucid Dreams", artist: "Juice WRLD", key: "F# Minor", bpm: 84, genre: "Hip-Hop" },
    { id: 342, title: "All Girls Are The Same", artist: "Juice WRLD", key: "C Minor", bpm: 162, genre: "Hip-Hop" },
    { id: 343, title: "Robbery", artist: "Juice WRLD", key: "D Major", bpm: 80, genre: "Hip-Hop" },
    { id: 344, title: "XO Tour Llif3", artist: "Lil Uzi Vert", key: "F# Minor", bpm: 155, genre: "Hip-Hop" },
    { id: 345, title: "The Way Life Goes", artist: "Lil Uzi Vert", key: "B Major", bpm: 82, genre: "Hip-Hop" },
    { id: 346, title: "Just Wanna Rock", artist: "Lil Uzi Vert", key: "G# Minor", bpm: 150, genre: "Hip-Hop" },
    { id: 347, title: "Congratulations", artist: "Post Malone", key: "F# Major", bpm: 123, genre: "Hip-Hop" },
    { id: 348, title: "Rockstar", artist: "Post Malone", key: "F Minor", bpm: 160, genre: "Hip-Hop" },
    { id: 349, title: "Sunflower", artist: "Post Malone & Swae Lee", key: "D Major", bpm: 90, genre: "Hip-Hop" },
    { id: 350, title: "Better Now", artist: "Post Malone", key: "Bb Major", bpm: 145, genre: "Hip-Hop" },
    { id: 351, title: "Circles", artist: "Post Malone", key: "C Major", bpm: 120, genre: "Hip-Hop" },
    { id: 352, title: "SAD!", artist: "XXXTENTACION", key: "Ab Major", bpm: 75, genre: "Hip-Hop" },
    { id: 353, title: "Moonlight", artist: "XXXTENTACION", key: "A Minor", bpm: 128, genre: "Hip-Hop" },
    { id: 354, title: "Jocelyn Flores", artist: "XXXTENTACION", key: "B Minor", bpm: 134, genre: "Hip-Hop" },
    { id: 355, title: "Look At Me!", artist: "XXXTENTACION", key: "A Minor", bpm: 139, genre: "Hip-Hop" },
    { id: 356, title: "Suge", artist: "DaBaby", key: "F# Minor", bpm: 152, genre: "Hip-Hop" },
    { id: 357, title: "Rockstar", artist: "DaBaby ft. Roddy Ricch", key: "G# Minor", bpm: 90, genre: "Hip-Hop" },
    { id: 358, title: "The Box", artist: "Roddy Ricch", key: "Ab Minor", bpm: 117, genre: "Hip-Hop" },
    { id: 359, title: "High Fashion", artist: "Roddy Ricch", key: "F Minor", bpm: 98, genre: "Hip-Hop" },
    { id: 360, title: "Drip Too Hard", artist: "Lil Baby & Gunna", key: "Bb Minor", bpm: 113, genre: "Hip-Hop" },
    { id: 361, title: "Yes Indeed", artist: "Lil Baby & Drake", key: "F Minor", bpm: 120, genre: "Hip-Hop" },
    { id: 362, title: "Life Is Good", artist: "Future ft. Drake", key: "F Minor", bpm: 142, genre: "Hip-Hop" },
    { id: 363, title: "Mask Off", artist: "Future", key: "C# Minor", bpm: 150, genre: "Hip-Hop" },
    { id: 364, title: "Low Life", artist: "Future ft. The Weeknd", key: "G Minor", bpm: 144, genre: "Hip-Hop" },
    { id: 365, title: "Bad and Boujee", artist: "Migos ft. Lil Uzi Vert", key: "Eb Minor", bpm: 127, genre: "Hip-Hop" },
    { id: 366, title: "Slippery", artist: "Migos", key: "A Minor", bpm: 142, genre: "Hip-Hop" },
    { id: 367, title: "Walk It Talk It", artist: "Migos ft. Drake", key: "F# Minor", bpm: 146, genre: "Hip-Hop" },
    { id: 368, title: "Work", artist: "Rihanna ft. Drake", key: "C# Minor", bpm: 92, genre: "Hip-Hop" },
    { id: 369, title: "Needed Me", artist: "Rihanna", key: "F Minor", bpm: 111, genre: "Hip-Hop" },
    { id: 370, title: "Bodak Yellow", artist: "Cardi B", key: "B Major", bpm: 125, genre: "Hip-Hop" },
    { id: 371, title: "I Like It", artist: "Cardi B, Bad Bunny & J Balvin", key: "F Minor", bpm: 136, genre: "Hip-Hop" },
    { id: 372, title: "WAP", artist: "Cardi B ft. Megan Thee Stallion", key: "A Minor", bpm: 133, genre: "Hip-Hop" },
    { id: 373, title: "Savage", artist: "Megan Thee Stallion", key: "B Minor", bpm: 169, genre: "Hip-Hop" },
    { id: 374, title: "Hot Girl Summer", artist: "Megan Thee Stallion", key: "G# Major", bpm: 99, genre: "Hip-Hop" },
    { id: 375, title: "Truth Hurts", artist: "Lizzo", key: "C Major", bpm: 158, genre: "Hip-Hop" },
    { id: 376, title: "Old Town Road", artist: "Lil Nas X", key: "G# Minor", bpm: 136, genre: "Hip-Hop" },
    { id: 377, title: "Panini", artist: "Lil Nas X", key: "F Minor", bpm: 154, genre: "Hip-Hop" },
    { id: 378, title: "Rodeo", artist: "Lil Nas X & Cardi B", key: "G# Minor", bpm: 140, genre: "Hip-Hop" },
    { id: 379, title: "Holiday", artist: "Lil Nas X", key: "A Minor", bpm: 151, genre: "Hip-Hop" },
    { id: 380, title: "Super Bass", artist: "Nicki Minaj", key: "B Major", bpm: 127, genre: "Hip-Hop" },
    { id: 381, title: "Starships", artist: "Nicki Minaj", key: "D Major", bpm: 125, genre: "Hip-Hop" },
    { id: 382, title: "Anaconda", artist: "Nicki Minaj", key: "C Minor", bpm: 130, genre: "Hip-Hop" },
    { id: 383, title: "Chun-Li", artist: "Nicki Minaj", key: "C# Minor", bpm: 97, genre: "Hip-Hop" },
    { id: 384, title: "Empire State of Mind", artist: "Jay-Z ft. Alicia Keys", key: "F# Major", bpm: 173, genre: "Hip-Hop" },
    { id: 385, title: "Niggas in Paris", artist: "Jay-Z & Kanye West", key: "C Minor", bpm: 140, genre: "Hip-Hop" },
    { id: 386, title: "Stronger", artist: "Kanye West", key: "Bb Minor", bpm: 104, genre: "Hip-Hop" },
    { id: 387, title: "Heartless", artist: "Kanye West", key: "Bb Minor", bpm: 88, genre: "Hip-Hop" },
    { id: 388, title: "Power", artist: "Kanye West", key: "C Minor", bpm: 154, genre: "Hip-Hop" },
    { id: 389, title: "Gold Digger", artist: "Kanye West", key: "Ab Major", bpm: 93, genre: "Hip-Hop" },
    { id: 390, title: "Ms. Jackson", artist: "Outkast", key: "F# Minor", bpm: 95, genre: "Hip-Hop" },
    { id: 391, title: "Hey Ya!", artist: "Outkast", key: "G Major", bpm: 160, genre: "Hip-Hop" },
    { id: 392, title: "Lose Control", artist: "Missy Elliott", key: "C Minor", bpm: 125, genre: "Hip-Hop" },
    { id: 393, title: "Get Ur Freak On", artist: "Missy Elliott", key: "F Minor", bpm: 177, genre: "Hip-Hop" },
    { id: 394, title: "In Da Club", artist: "50 Cent", key: "F# Minor", bpm: 90, genre: "Hip-Hop" },
    { id: 395, title: "Candy Shop", artist: "50 Cent", key: "B Major", bpm: 125, genre: "Hip-Hop" },
    { id: 396, title: "Still D.R.E.", artist: "Dr. Dre ft. Snoop Dogg", key: "A Minor", bpm: 93, genre: "Hip-Hop" },
    { id: 397, title: "The Next Episode", artist: "Dr. Dre ft. Snoop Dogg", key: "D Minor", bpm: 190, genre: "Hip-Hop" },
    { id: 398, title: "Gin and Juice", artist: "Snoop Dogg", key: "A Minor", bpm: 95, genre: "Hip-Hop" },
    { id: 399, title: "California Love", artist: "2Pac ft. Dr. Dre", key: "G Major", bpm: 92, genre: "Hip-Hop" },
    { id: 400, title: "Juicy", artist: "The Notorious B.I.G.", key: "A Major", bpm: 96, genre: "Hip-Hop" },

    // ROCK SECTION - Top 100 Rock Songs
    { id: 401, title: "Stairway to Heaven", artist: "Led Zeppelin", key: "A Minor", bpm: 82, genre: "Rock" },
    { id: 402, title: "Whole Lotta Love", artist: "Led Zeppelin", key: "E Minor", bpm: 89, genre: "Rock" },
    { id: 403, title: "Kashmir", artist: "Led Zeppelin", key: "D Major", bpm: 80, genre: "Rock" },
    { id: 404, title: "Black Dog", artist: "Led Zeppelin", key: "A Minor", bpm: 82, genre: "Rock" },
    { id: 405, title: "Immigrant Song", artist: "Led Zeppelin", key: "F# Minor", bpm: 112, genre: "Rock" },
    { id: 406, title: "Rock and Roll", artist: "Led Zeppelin", key: "A Major", bpm: 170, genre: "Rock" },
    { id: 407, title: "Thunderstruck", artist: "AC/DC", key: "B Major", bpm: 134, genre: "Rock" },
    { id: 408, title: "Back In Black", artist: "AC/DC", key: "E Minor", bpm: 94, genre: "Rock" },
    { id: 409, title: "Highway to Hell", artist: "AC/DC", key: "A Major", bpm: 116, genre: "Rock" },
    { id: 410, title: "You Shook Me All Night Long", artist: "AC/DC", key: "G Major", bpm: 127, genre: "Rock" },
    { id: 411, title: "T.N.T.", artist: "AC/DC", key: "E Major", bpm: 126, genre: "Rock" },
    { id: 412, title: "Dream On", artist: "Aerosmith", key: "F Minor", bpm: 80, genre: "Rock" },
    { id: 413, title: "Walk This Way", artist: "Aerosmith", key: "C Major", bpm: 109, genre: "Rock" },
    { id: 414, title: "I Don't Want to Miss a Thing", artist: "Aerosmith", key: "D Major", bpm: 121, genre: "Rock" },
    { id: 415, title: "Sweet Emotion", artist: "Aerosmith", key: "A Major", bpm: 99, genre: "Rock" },
    { id: 416, title: "Crazy", artist: "Aerosmith", key: "A Major", bpm: 110, genre: "Rock" },
    { id: 417, title: "Free Bird", artist: "Lynyrd Skynyrd", key: "G Major", bpm: 143, genre: "Rock" },
    { id: 418, title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", key: "D Major", bpm: 98, genre: "Rock" },
    { id: 419, title: "Simple Man", artist: "Lynyrd Skynyrd", key: "C Major", bpm: 122, genre: "Rock" },
    { id: 420, title: "Fortunate Son", artist: "Creedence Clearwater Revival", key: "G Major", bpm: 133, genre: "Rock" },
    { id: 421, title: "Have You Ever Seen the Rain", artist: "Creedence Clearwater Revival", key: "C Major", bpm: 116, genre: "Rock" },
    { id: 422, title: "Bad Moon Rising", artist: "Creedence Clearwater Revival", key: "D Major", bpm: 179, genre: "Rock" },
    { id: 423, title: "Proud Mary", artist: "Creedence Clearwater Revival", key: "D Major", bpm: 121, genre: "Rock" },
    { id: 424, title: "Sympathy for the Devil", artist: "The Rolling Stones", key: "E Major", bpm: 116, genre: "Rock" },
    { id: 425, title: "Paint It, Black", artist: "The Rolling Stones", key: "E Minor", bpm: 159, genre: "Rock" },
    { id: 426, title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", key: "E Major", bpm: 136, genre: "Rock" },
    { id: 427, title: "Gimme Shelter", artist: "The Rolling Stones", key: "C# Minor", bpm: 119, genre: "Rock" },
    { id: 428, title: "Start Me Up", artist: "The Rolling Stones", key: "F Major", bpm: 122, genre: "Rock" },
    { id: 429, title: "Angie", artist: "The Rolling Stones", key: "A Minor", bpm: 136, genre: "Rock" },
    { id: 430, title: "Comfortably Numb", artist: "Pink Floyd", key: "B Minor", bpm: 127, genre: "Rock" },
    { id: 431, title: "Wish You Were Here", artist: "Pink Floyd", key: "G Major", bpm: 60, genre: "Rock" },
    { id: 432, title: "Another Brick in the Wall, Pt. 2", artist: "Pink Floyd", key: "D Minor", bpm: 104, genre: "Rock" },
    { id: 433, title: "Money", artist: "Pink Floyd", key: "B Minor", bpm: 120, genre: "Rock" },
    { id: 434, title: "Time", artist: "Pink Floyd", key: "F# Minor", bpm: 122, genre: "Rock" },
    { id: 435, title: "Purple Haze", artist: "Jimi Hendrix", key: "E Minor", bpm: 109, genre: "Rock" },
    { id: 436, title: "All Along the Watchtower", artist: "Jimi Hendrix", key: "C# Minor", bpm: 115, genre: "Rock" },
    { id: 437, title: "Voodoo Child (Slight Return)", artist: "Jimi Hendrix", key: "E Minor", bpm: 179, genre: "Rock" },
    { id: 438, title: "Little Wing", artist: "Jimi Hendrix", key: "E Minor", bpm: 71, genre: "Rock" },
    { id: 439, title: "Hey Joe", artist: "Jimi Hendrix", key: "E Major", bpm: 82, genre: "Rock" },
    { id: 440, title: "Smoke on the Water", artist: "Deep Purple", key: "G Minor", bpm: 114, genre: "Rock" },
    { id: 441, title: "Highway Star", artist: "Deep Purple", key: "G Minor", bpm: 173, genre: "Rock" },
    { id: 442, title: "Paranoid", artist: "Black Sabbath", key: "E Minor", bpm: 163, genre: "Rock" },
    { id: 443, title: "Iron Man", artist: "Black Sabbath", key: "B Minor", bpm: 74, genre: "Rock" },
    { id: 444, title: "War Pigs", artist: "Black Sabbath", key: "E Minor", bpm: 92, genre: "Rock" },
    { id: 445, title: "Killer Queen", artist: "Queen", key: "Eb Major", bpm: 117, genre: "Rock" },
    { id: 446, title: "Don't Stop Me Now", artist: "Queen", key: "F Major", bpm: 156, genre: "Rock" },
    { id: 447, title: "Somebody to Love", artist: "Queen", key: "Ab Major", bpm: 111, genre: "Rock" },
    { id: 448, title: "Radio Ga Ga", artist: "Queen", key: "F Major", bpm: 112, genre: "Rock" },
    { id: 449, title: "The Show Must Go On", artist: "Queen", key: "B Minor", bpm: 84, genre: "Rock" },
    { id: 450, title: "Layla", artist: "Derek & The Dominos", key: "D Minor", bpm: 116, genre: "Rock" },
    { id: 451, title: "Cocaine", artist: "Eric Clapton", key: "E Minor", bpm: 105, genre: "Rock" },
    { id: 452, title: "Tears in Heaven", artist: "Eric Clapton", key: "A Major", bpm: 153, genre: "Rock" },
    { id: 453, title: "Wonderful Tonight", artist: "Eric Clapton", key: "G Major", bpm: 95, genre: "Rock" },
    { id: 454, title: "Sultans of Swing", artist: "Dire Straits", key: "D Minor", bpm: 148, genre: "Rock" },
    { id: 455, title: "Money for Nothing", artist: "Dire Straits", key: "G Minor", bpm: 134, genre: "Rock" },
    { id: 456, title: "Walk of Life", artist: "Dire Straits", key: "E Major", bpm: 172, genre: "Rock" },
    { id: 457, title: "Born to Run", artist: "Bruce Springsteen", key: "E Major", bpm: 146, genre: "Rock" },
    { id: 458, title: "Dancing in the Dark", artist: "Bruce Springsteen", key: "B Major", bpm: 149, genre: "Rock" },
    { id: 459, title: "Born in the U.S.A.", artist: "Bruce Springsteen", key: "B Major", bpm: 122, genre: "Rock" },
    { id: 460, title: "Piano Man", artist: "Billy Joel", key: "C Major", bpm: 178, genre: "Rock" },
    { id: 461, title: "Uptown Girl", artist: "Billy Joel", key: "E Major", bpm: 129, genre: "Rock" },
    { id: 462, title: "We Didn't Start the Fire", artist: "Billy Joel", key: "G Major", bpm: 144, genre: "Rock" },
    { id: 463, title: "More Than a Feeling", artist: "Boston", key: "G Major", bpm: 109, genre: "Rock" },
    { id: 464, title: "Barracuda", artist: "Heart", key: "E Minor", bpm: 135, genre: "Rock" },
    { id: 465, title: "Alone", artist: "Heart", key: "Bb Minor", bpm: 173, genre: "Rock" },
    { id: 466, title: "Edge of Seventeen", artist: "Stevie Nicks", key: "E Minor", bpm: 114, genre: "Rock" },
    { id: 467, title: "Landslide", artist: "Fleetwood Mac", key: "Eb Major", bpm: 159, genre: "Rock" },
    { id: 468, title: "Dreams", artist: "Fleetwood Mac", key: "F Major", bpm: 120, genre: "Rock" },
    { id: 469, title: "Go Your Own Way", artist: "Fleetwood Mac", key: "F Major", bpm: 136, genre: "Rock" },
    { id: 470, title: "The Chain", artist: "Fleetwood Mac", key: "E Minor", bpm: 152, genre: "Rock" },
    { id: 471, title: "Don't Stop", artist: "Fleetwood Mac", key: "E Major", bpm: 120, genre: "Rock" },
    { id: 472, title: "Hotel California", artist: "Eagles", key: "B Minor", bpm: 74, genre: "Rock" },
    { id: 473, title: "Take It Easy", artist: "Eagles", key: "G Major", bpm: 138, genre: "Rock" },
    { id: 474, title: "Life in the Fast Lane", artist: "Eagles", key: "E Major", bpm: 109, genre: "Rock" },
    { id: 475, title: "Desperado", artist: "Eagles", key: "G Major", bpm: 126, genre: "Rock" },
    { id: 476, title: "Seven Nation Army", artist: "The White Stripes", key: "E Minor", bpm: 124, genre: "Rock" },
    { id: 477, title: "Mr. Brightside", artist: "The Killers", key: "Db Major", bpm: 148, genre: "Rock" },
    { id: 478, title: "Somebody Told Me", artist: "The Killers", key: "Bb Minor", bpm: 138, genre: "Rock" },
    { id: 479, title: "When You Were Young", artist: "The Killers", key: "B Major", bpm: 131, genre: "Rock" },
    { id: 480, title: "Sex on Fire", artist: "Kings of Leon", key: "E Major", bpm: 153, genre: "Rock" },
    { id: 481, title: "Use Somebody", artist: "Kings of Leon", key: "C Major", bpm: 137, genre: "Rock" },
    { id: 482, title: "Everlong", artist: "Foo Fighters", key: "D Major", bpm: 158, genre: "Rock" },
    { id: 483, title: "The Pretender", artist: "Foo Fighters", key: "A Minor", bpm: 173, genre: "Rock" },
    { id: 484, title: "Best of You", artist: "Foo Fighters", key: "C# Minor", bpm: 130, genre: "Rock" },
    { id: 485, title: "Learn to Fly", artist: "Foo Fighters", key: "B Major", bpm: 136, genre: "Rock" },
    { id: 486, title: "My Hero", artist: "Foo Fighters", key: "E Major", bpm: 77, genre: "Rock" },
    { id: 487, title: "Chop Suey!", artist: "System Of A Down", key: "G Minor", bpm: 127, genre: "Rock" },
    { id: 488, title: "Toxicity", artist: "System Of A Down", key: "C Minor", bpm: 114, genre: "Rock" },
    { id: 489, title: "B.Y.O.B.", artist: "System Of A Down", key: "C# Minor", bpm: 105, genre: "Rock" },
    { id: 490, title: "In the End", artist: "Linkin Park", key: "Eb Minor", bpm: 105, genre: "Rock" },
    { id: 491, title: "Numb", artist: "Linkin Park", key: "F# Minor", bpm: 110, genre: "Rock" },
    { id: 492, title: "Crawling", artist: "Linkin Park", key: "C# Minor", bpm: 105, genre: "Rock" },
    { id: 493, title: "One Step Closer", artist: "Linkin Park", key: "C# Minor", bpm: 95, genre: "Rock" },
    { id: 494, title: "Breaking the Habit", artist: "Linkin Park", key: "F Minor", bpm: 100, genre: "Rock" },
    { id: 495, title: "Last Resort", artist: "Papa Roach", key: "E Minor", bpm: 91, genre: "Rock" },
    { id: 496, title: "Bring Me to Life", artist: "Evanescence", key: "E Minor", bpm: 95, genre: "Rock" },
    { id: 497, title: "My Immortal", artist: "Evanescence", key: "A Major", bpm: 78, genre: "Rock" },
    { id: 498, title: "Kryptonite", artist: "3 Doors Down", key: "B Minor", bpm: 99, genre: "Rock" },
    { id: 499, title: "How You Remind Me", artist: "Nickelback", key: "C Minor", bpm: 86, genre: "Rock" },
    { id: 500, title: "Photograph", artist: "Nickelback", key: "Eb Major", bpm: 76, genre: "Rock" },

    // R&B SECTION - Top 100 R&B Songs
    { id: 501, title: "Kill Bill", artist: "SZA", key: "Ab Major", bpm: 89, genre: "R&B" },
    { id: 502, title: "Snooze", artist: "SZA", key: "F# Major", bpm: 143, genre: "R&B" },
    { id: 503, title: "Good Days", artist: "SZA", key: "E Major", bpm: 121, genre: "R&B" },
    { id: 504, title: "Kiss Me More", artist: "Doja Cat ft. SZA", key: "Ab Major", bpm: 111, genre: "R&B" },
    { id: 505, title: "I Hate U", artist: "SZA", key: "F# Minor", bpm: 106, genre: "R&B" },
    { id: 506, title: "Shirt", artist: "SZA", key: "C# Minor", bpm: 120, genre: "R&B" },
    { id: 507, title: "Nobody Gets Me", artist: "SZA", key: "G Major", bpm: 100, genre: "R&B" },
    { id: 508, title: "Low", artist: "SZA", key: "F Minor", bpm: 106, genre: "R&B" },
    { id: 509, title: "Blind", artist: "SZA", key: "B Minor", bpm: 133, genre: "R&B" },
    { id: 510, title: "Broken Clocks", artist: "SZA", key: "Bb Major", bpm: 121, genre: "R&B" },
    { id: 511, title: "The Weekend", artist: "SZA", key: "A Major", bpm: 102, genre: "R&B" },
    { id: 512, title: "Love Galore", artist: "SZA ft. Travis Scott", key: "C# Minor", bpm: 135, genre: "R&B" },
    { id: 513, title: "Supermodel", artist: "SZA", key: "C# Major", bpm: 79, genre: "R&B" },
    { id: 514, title: "Garden (Say It Like Dat)", artist: "SZA", key: "B Major", bpm: 112, genre: "R&B" },
    { id: 515, title: "Drew Barrymore", artist: "SZA", key: "G Major", bpm: 136, genre: "R&B" },
    { id: 516, title: "Die For You", artist: "The Weeknd", key: "C# Minor", bpm: 133, genre: "R&B" },
    { id: 517, title: "The Hills", artist: "The Weeknd", key: "C Minor", bpm: 113, genre: "R&B" },
    { id: 518, title: "Call Out My Name", artist: "The Weeknd", key: "D# Minor", bpm: 45, genre: "R&B" },
    { id: 519, title: "Earned It", artist: "The Weeknd", key: "D Minor", bpm: 120, genre: "R&B" },
    { id: 520, title: "Wicked Games", artist: "The Weeknd", key: "B Minor", bpm: 114, genre: "R&B" },
    { id: 521, title: "Often", artist: "The Weeknd", key: "G Minor", bpm: 134, genre: "R&B" },
    { id: 522, title: "Acquainted", artist: "The Weeknd", key: "G Minor", bpm: 106, genre: "R&B" },
    { id: 523, title: "Heartless", artist: "The Weeknd", key: "Bb Minor", bpm: 170, genre: "R&B" },
    { id: 524, title: "Reminder", artist: "The Weeknd", key: "Ab Minor", bpm: 160, genre: "R&B" },
    { id: 525, title: "Starboy", artist: "The Weeknd ft. Daft Punk", key: "G Major", bpm: 186, genre: "R&B" },
    { id: 526, title: "Cuff It", artist: "Beyoncé", key: "B Minor", bpm: 115, genre: "R&B" },
    { id: 527, title: "Break My Soul", artist: "Beyoncé", key: "G# Minor", bpm: 115, genre: "R&B" },
    { id: 528, title: "Alien Superstar", artist: "Beyoncé", key: "A Minor", bpm: 121, genre: "R&B" },
    { id: 529, title: "Drunk in Love", artist: "Beyoncé ft. Jay-Z", key: "F Minor", bpm: 140, genre: "R&B" },
    { id: 530, title: "Partition", artist: "Beyoncé", key: "E Minor", bpm: 185, genre: "R&B" },
    { id: 531, title: "Formation", artist: "Beyoncé", key: "F Minor", bpm: 122, genre: "R&B" },
    { id: 532, title: "Love on Top", artist: "Beyoncé", key: "C Major", bpm: 94, genre: "R&B" },
    { id: 533, title: "Halo", artist: "Beyoncé", key: "A Major", bpm: 80, genre: "R&B" },
    { id: 534, title: "Irreplaceable", artist: "Beyoncé", key: "Bb Major", bpm: 88, genre: "R&B" },
    { id: 535, title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé", key: "E Major", bpm: 97, genre: "R&B" },
    { id: 536, title: "Crazy In Love", artist: "Beyoncé ft. Jay-Z", key: "D Minor", bpm: 99, genre: "R&B" },
    { id: 537, title: "Leave The Door Open", artist: "Bruno Mars, Anderson .Paak, Silk Sonic", key: "D Major", bpm: 148, genre: "R&B" },
    { id: 538, title: "Smokin Out The Window", artist: "Bruno Mars, Anderson .Paak, Silk Sonic", key: "D Minor", bpm: 82, genre: "R&B" },
    { id: 539, title: "That's What I Like", artist: "Bruno Mars", key: "Bb Minor", bpm: 134, genre: "R&B" },
    { id: 540, title: "24K Magic", artist: "Bruno Mars", key: "F Minor", bpm: 107, genre: "R&B" },
    { id: 541, title: "Versace on the Floor", artist: "Bruno Mars", key: "D Major", bpm: 87, genre: "R&B" },
    { id: 542, title: "Finesse", artist: "Bruno Mars ft. Cardi B", key: "F Minor", bpm: 105, genre: "R&B" },
    { id: 543, title: "Treasure", artist: "Bruno Mars", key: "Ab Major", bpm: 116, genre: "R&B" },
    { id: 544, title: "When I Was Your Man", artist: "Bruno Mars", key: "C Major", bpm: 73, genre: "R&B" },
    { id: 545, title: "Talking to the Moon", artist: "Bruno Mars", key: "E Major", bpm: 146, genre: "R&B" },
    { id: 546, title: "Location", artist: "Khalid", key: "C Major", bpm: 80, genre: "R&B" },
    { id: 547, title: "Young Dumb & Broke", artist: "Khalid", key: "C Major", bpm: 137, genre: "R&B" },
    { id: 548, title: "Talk", artist: "Khalid", key: "C Major", bpm: 136, genre: "R&B" },
    { id: 549, title: "Better", artist: "Khalid", key: "G Major", bpm: 98, genre: "R&B" },
    { id: 550, title: "Eastside", artist: "Benny Blanco, Halsey & Khalid", key: "F# Major", bpm: 89, genre: "R&B" },
    { id: 551, title: "Best Part", artist: "Daniel Caesar ft. H.E.R.", key: "D Major", bpm: 75, genre: "R&B" },
    { id: 552, title: "Get You", artist: "Daniel Caesar ft. Kali Uchis", key: "D Major", bpm: 93, genre: "R&B" },
    { id: 553, title: "Japanese Denim", artist: "Daniel Caesar", key: "E Major", bpm: 120, genre: "R&B" },
    { id: 554, title: "Peaches", artist: "Justin Bieber ft. Daniel Caesar & Giveon", key: "C Major", bpm: 90, genre: "R&B" },
    { id: 555, title: "Heartbreak Anniversary", artist: "Giveon", key: "C Major", bpm: 89, genre: "R&B" },
    { id: 556, title: "Like I Want You", artist: "Giveon", key: "A Minor", bpm: 96, genre: "R&B" },
    { id: 557, title: "For Tonight", artist: "Giveon", key: "G# Minor", bpm: 80, genre: "R&B" },
    { id: 558, title: "Hrs & Hrs", artist: "Muni Long", key: "A Major", bpm: 115, genre: "R&B" },
    { id: 559, title: "Made For Me", artist: "Muni Long", key: "Eb Major", bpm: 136, genre: "R&B" },
    { id: 560, title: "Essence", artist: "Wizkid ft. Tems", key: "Eb Minor", bpm: 104, genre: "R&B" },
    { id: 561, title: "Free Mind", artist: "Tems", key: "A Minor", bpm: 108, genre: "R&B" },
    { id: 562, title: "Higher", artist: "Tems", key: "G# Minor", bpm: 100, genre: "R&B" },
    { id: 563, title: "Water", artist: "Tyla", key: "C# Minor", bpm: 117, genre: "R&B" },
    { id: 564, title: "Damage", artist: "H.E.R.", key: "Db Major", bpm: 81, genre: "R&B" },
    { id: 565, title: "Focus", artist: "H.E.R.", key: "G# Minor", bpm: 88, genre: "R&B" },
    { id: 566, title: "Could've Been", artist: "H.E.R. ft. Bryson Tiller", key: "Ab Major", bpm: 94, genre: "R&B" },
    { id: 567, title: "Slide", artist: "H.E.R. ft. YG", key: "Eb Minor", bpm: 97, genre: "R&B" },
    { id: 568, title: "Trip", artist: "Ella Mai", key: "F# Major", bpm: 81, genre: "R&B" },
    { id: 569, title: "Boo'd Up", artist: "Ella Mai", key: "Ab Major", bpm: 82, genre: "R&B" },
    { id: 570, title: "Shot Clock", artist: "Ella Mai", key: "C# Minor", bpm: 96, genre: "R&B" },
    { id: 571, title: "Exchange", artist: "Bryson Tiller", key: "F# Minor", bpm: 160, genre: "R&B" },
    { id: 572, title: "Don't", artist: "Bryson Tiller", key: "B Minor", bpm: 97, genre: "R&B" },
    { id: 573, title: "Sorrows", artist: "Bryson Tiller", key: "C# Minor", bpm: 121, genre: "R&B" },
    { id: 574, title: "Wild Thoughts", artist: "DJ Khaled ft. Rihanna", key: "C Minor", bpm: 98, genre: "R&B" },
    { id: 575, title: "Diamonds", artist: "Rihanna", key: "B Minor", bpm: 92, genre: "R&B" },
    { id: 576, title: "Stay", artist: "Rihanna ft. Mikky Ekko", key: "C Major", bpm: 112, genre: "R&B" },
    { id: 577, title: "Love on the Brain", artist: "Rihanna", key: "G Major", bpm: 57, genre: "R&B" },
    { id: 578, title: "Umbrella", artist: "Rihanna", key: "Bb Minor", bpm: 174, genre: "R&B" },
    { id: 579, title: "No One", artist: "Alicia Keys", key: "E Major", bpm: 90, genre: "R&B" },
    { id: 580, title: "If I Ain't Got You", artist: "Alicia Keys", key: "G Major", bpm: 118, genre: "R&B" },
    { id: 581, title: "Fallin'", artist: "Alicia Keys", key: "E Minor", bpm: 96, genre: "R&B" },
    { id: 582, title: "Girl on Fire", artist: "Alicia Keys", key: "A Major", bpm: 93, genre: "R&B" },
    { id: 583, title: "My Boo", artist: "Usher & Alicia Keys", key: "F Major", bpm: 86, genre: "R&B" },
    { id: 584, title: "Yeah!", artist: "Usher ft. Lil Jon", key: "G Minor", bpm: 105, genre: "R&B" },
    { id: 585, title: "Burn", artist: "Usher", key: "C# Major", bpm: 60, genre: "R&B" },
    { id: 586, title: "Confessions Part II", artist: "Usher", key: "F Minor", bpm: 128, genre: "R&B" },
    { id: 587, title: "U Got It Bad", artist: "Usher", key: "Bb Minor", bpm: 126, genre: "R&B" },
    { id: 588, title: "We Belong Together", artist: "Mariah Carey", key: "C Major", bpm: 140, genre: "R&B" },
    { id: 589, title: "Obsessed", artist: "Mariah Carey", key: "C Minor", bpm: 85, genre: "R&B" },
    { id: 590, title: "Fantasy", artist: "Mariah Carey", key: "G Major", bpm: 102, genre: "R&B" },
    { id: 591, title: "Always Be My Baby", artist: "Mariah Carey", key: "E Major", bpm: 139, genre: "R&B" },
    { id: 592, title: "Hero", artist: "Mariah Carey", key: "E Major", bpm: 60, genre: "R&B" },
    { id: 593, title: "Adorn", artist: "Miguel", key: "A Major", bpm: 110, genre: "R&B" },
    { id: 594, title: "Sure Thing", artist: "Miguel", key: "E Minor", bpm: 81, genre: "R&B" },
    { id: 595, title: "Sky Walker", artist: "Miguel ft. Travis Scott", key: "C# Major", bpm: 146, genre: "R&B" },
    { id: 596, title: "Come Through and Chill", artist: "Miguel ft. J. Cole", key: "D Minor", bpm: 82, genre: "R&B" },
    { id: 597, title: "Coffee", artist: "Miguel", key: "A Major", bpm: 105, genre: "R&B" },
    { id: 598, title: "Redbone", artist: "Childish Gambino", key: "Bb Minor", bpm: 160, genre: "R&B" },
    { id: 599, title: "Sober", artist: "Childish Gambino", key: "G# Major", bpm: 115, genre: "R&B" },
    { id: 600, title: "Heartbeat", artist: "Childish Gambino", key: "F# Minor", bpm: 118, genre: "R&B" },

    // POP SECTION FILLER - Top 75 Extra Pop Songs
    { id: 601, title: "Houdini", artist: "Dua Lipa", key: "D Minor", bpm: 117, genre: "Pop" },
    { id: 602, title: "Training Season", artist: "Dua Lipa", key: "F Minor", bpm: 123, genre: "Pop" },
    { id: 603, title: "Dance The Night", artist: "Dua Lipa", key: "B Minor", bpm: 110, genre: "Pop" },
    { id: 604, title: "Physical", artist: "Dua Lipa", key: "C Minor", bpm: 147, genre: "Pop" },
    { id: 605, title: "New Rules", artist: "Dua Lipa", key: "A Minor", bpm: 116, genre: "Pop" },
    { id: 606, title: "Break My Heart", artist: "Dua Lipa", key: "E Minor", bpm: 113, genre: "Pop" },
    { id: 607, title: "Hallucinate", artist: "Dua Lipa", key: "Bb Minor", bpm: 122, genre: "Pop" },
    { id: 608, title: "One Kiss", artist: "Calvin Harris & Dua Lipa", key: "A Minor", bpm: 124, genre: "Pop" },
    { id: 609, title: "Electricity", artist: "Silk City & Dua Lipa", key: "C Minor", bpm: 118, genre: "Pop" },
    { id: 610, title: "IDGAF", artist: "Dua Lipa", key: "E Minor", bpm: 97, genre: "Pop" },
    { id: 611, title: "yes, and?", artist: "Ariana Grande", key: "Bb Major", bpm: 119, genre: "Pop" },
    { id: 612, title: "we can't be friends (wait for your love)", artist: "Ariana Grande", key: "F Major", bpm: 116, genre: "Pop" },
    { id: 613, title: "positions", artist: "Ariana Grande", key: "D Minor", bpm: 72, genre: "Pop" },
    { id: 614, title: "7 rings", artist: "Ariana Grande", key: "C# Minor", bpm: 70, genre: "Pop" },
    { id: 615, title: "thank u, next", artist: "Ariana Grande", key: "Db Major", bpm: 107, genre: "Pop" },
    { id: 616, title: "No Tears Left to Cry", artist: "Ariana Grande", key: "A Minor", bpm: 122, genre: "Pop" },
    { id: 617, title: "Into You", artist: "Ariana Grande", key: "F# Minor", bpm: 108, genre: "Pop" },
    { id: 618, title: "Side To Side", artist: "Ariana Grande ft. Nicki Minaj", key: "F# Minor", bpm: 159, genre: "Pop" },
    { id: 619, title: "Dangerous Woman", artist: "Ariana Grande", key: "E Minor", bpm: 67, genre: "Pop" },
    { id: 620, title: "One Last Time", artist: "Ariana Grande", key: "Ab Major", bpm: 125, genre: "Pop" },
    { id: 621, title: "Break Free", artist: "Ariana Grande ft. Zedd", key: "G Minor", bpm: 130, genre: "Pop" },
    { id: 622, title: "Problem", artist: "Ariana Grande ft. Iggy Azalea", key: "G# Minor", bpm: 103, genre: "Pop" },
    { id: 623, title: "Bang Bang", artist: "Jessie J, Ariana Grande, Nicki Minaj", key: "C Major", bpm: 150, genre: "Pop" },
    { id: 624, title: "Stuck with U", artist: "Ariana Grande & Justin Bieber", key: "Ab Major", bpm: 60, genre: "Pop" },
    { id: 625, title: "Rain On Me", artist: "Lady Gaga & Ariana Grande", key: "C# Minor", bpm: 123, genre: "Pop" },
    { id: 626, title: "Bad Romance", artist: "Lady Gaga", key: "C Major", bpm: 119, genre: "Pop" },
    { id: 627, title: "Poker Face", artist: "Lady Gaga", key: "G# Minor", bpm: 119, genre: "Pop" },
    { id: 628, title: "Just Dance", artist: "Lady Gaga", key: "C# Minor", bpm: 119, genre: "Pop" },
    { id: 629, title: "Born This Way", artist: "Lady Gaga", key: "B Major", bpm: 124, genre: "Pop" },
    { id: 630, title: "Applause", artist: "Lady Gaga", key: "G Minor", bpm: 140, genre: "Pop" },
    { id: 631, title: "Telephone", artist: "Lady Gaga ft. Beyoncé", key: "F Minor", bpm: 122, genre: "Pop" },
    { id: 632, title: "Shallow", artist: "Lady Gaga & Bradley Cooper", key: "G Major", bpm: 96, genre: "Pop" },
    { id: 633, title: "Always Remember Us This Way", artist: "Lady Gaga", key: "A Minor", bpm: 65, genre: "Pop" },
    { id: 634, title: "Million Reasons", artist: "Lady Gaga", key: "C Major", bpm: 65, genre: "Pop" },
    { id: 635, title: "Stupid Love", artist: "Lady Gaga", key: "Bb Major", bpm: 118, genre: "Pop" },
    { id: 636, title: "Firework", artist: "Katy Perry", key: "Ab Major", bpm: 124, genre: "Pop" },
    { id: 637, title: "Roar", artist: "Katy Perry", key: "Bb Major", bpm: 90, genre: "Pop" },
    { id: 638, title: "Dark Horse", artist: "Katy Perry", key: "Bb Minor", bpm: 132, genre: "Pop" },
    { id: 639, title: "Last Friday Night (T.G.I.F.)", artist: "Katy Perry", key: "F# Major", bpm: 126, genre: "Pop" },
    { id: 640, title: "California Gurls", artist: "Katy Perry ft. Snoop Dogg", key: "C Major", bpm: 125, genre: "Pop" },
    { id: 641, title: "Teenage Dream", artist: "Katy Perry", key: "Bb Major", bpm: 120, genre: "Pop" },
    { id: 642, title: "Hot N Cold", artist: "Katy Perry", key: "G Major", bpm: 132, genre: "Pop" },
    { id: 643, title: "I Kissed A Girl", artist: "Katy Perry", key: "A Minor", bpm: 130, genre: "Pop" },
    { id: 644, title: "The One That Got Away", artist: "Katy Perry", key: "E Major", bpm: 134, genre: "Pop" },
    { id: 645, title: "E.T.", artist: "Katy Perry", key: "F Minor", bpm: 152, genre: "Pop" },
    { id: 646, title: "Chained To The Rhythm", artist: "Katy Perry", key: "A Minor", bpm: 95, genre: "Pop" },
    { id: 647, title: "Wide Awake", artist: "Katy Perry", key: "F Major", bpm: 80, genre: "Pop" },
    { id: 648, title: "Never Really Over", artist: "Katy Perry", key: "Ab Major", bpm: 135, genre: "Pop" },
    { id: 649, title: "Harleys In Hawaii", artist: "Katy Perry", key: "Bb Minor", bpm: 140, genre: "Pop" },
    { id: 650, title: "Daisies", artist: "Katy Perry", key: "F# Major", bpm: 122, genre: "Pop" },
    { id: 651, title: "Baby", artist: "Justin Bieber", key: "Eb Major", bpm: 65, genre: "Pop" },
    { id: 652, title: "Sorry", artist: "Justin Bieber", key: "Eb Major", bpm: 100, genre: "Pop" },
    { id: 653, title: "Love Yourself", artist: "Justin Bieber", key: "E Major", bpm: 100, genre: "Pop" },
    { id: 654, title: "What Do You Mean?", artist: "Justin Bieber", key: "Ab Major", bpm: 125, genre: "Pop" },
    { id: 655, title: "Yummy", artist: "Justin Bieber", key: "Bb Major", bpm: 146, genre: "Pop" },
    { id: 656, title: "Intentions", artist: "Justin Bieber", key: "A Major", bpm: 148, genre: "Pop" },
    { id: 657, title: "Holy", artist: "Justin Bieber ft. Chance The Rapper", key: "F# Major", bpm: 87, genre: "Pop" },
    { id: 658, title: "Lonely", artist: "Justin Bieber & benny blanco", key: "B Minor", bpm: 80, genre: "Pop" },
    { id: 659, title: "Anyone", artist: "Justin Bieber", key: "D Major", bpm: 116, genre: "Pop" },
    { id: 660, title: "Hold On", artist: "Justin Bieber", key: "C# Minor", bpm: 139, genre: "Pop" },
    { id: 661, title: "Boyfriend", artist: "Justin Bieber", key: "Bb Minor", bpm: 97, genre: "Pop" },
    { id: 662, title: "As Long As You Love Me", artist: "Justin Bieber", key: "C Minor", bpm: 140, genre: "Pop" },
    { id: 663, title: "Beauty and a Beat", artist: "Justin Bieber", key: "A Minor", bpm: 128, genre: "Pop" },
    { id: 664, title: "Company", artist: "Justin Bieber", key: "E Minor", bpm: 95, genre: "Pop" },
    { id: 665, title: "I Don't Care", artist: "Ed Sheeran & Justin Bieber", key: "F# Major", bpm: 102, genre: "Pop" },
    { id: 666, title: "Thinking Out Loud", artist: "Ed Sheeran", key: "D Major", bpm: 79, genre: "Pop" },
    { id: 667, title: "Perfect", artist: "Ed Sheeran", key: "Ab Major", bpm: 95, genre: "Pop" },
    { id: 668, title: "Photograph", artist: "Ed Sheeran", key: "E Major", bpm: 108, genre: "Pop" },
    { id: 669, title: "Bad Habits", artist: "Ed Sheeran", key: "B Minor", bpm: 126, genre: "Pop" },
    { id: 670, title: "Castle on the Hill", artist: "Ed Sheeran", key: "D Major", bpm: 135, genre: "Pop" },
    { id: 671, title: "Galway Girl", artist: "Ed Sheeran", key: "F# Minor", bpm: 100, genre: "Pop" },
    { id: 672, title: "Happier", artist: "Ed Sheeran", key: "C Major", bpm: 90, genre: "Pop" },
    { id: 673, title: "The A Team", artist: "Ed Sheeran", key: "A Major", bpm: 170, genre: "Pop" },
    { id: 674, title: "Lego House", artist: "Ed Sheeran", key: "B Major", bpm: 80, genre: "Pop" },
    { id: 675, title: "Eyes Closed", artist: "Ed Sheeran", key: "D Major", bpm: 107, genre: "Pop" },
];

export const searchSongs = async (query) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            if (!query) {
                resolve([]);
                return;
            }

            const lowerQuery = query.toLowerCase();
            const results = SONG_DATABASE.filter(song =>
                song.title.toLowerCase().includes(lowerQuery) ||
                song.artist.toLowerCase().includes(lowerQuery)
            );

            // Sort with priority:
            // 1. Exact title matches first
            // 2. Songs with cover art
            // 3. Then by popularity (ID)
            results.sort((a, b) => {
                const aExactMatch = a.title.toLowerCase() === lowerQuery;
                const bExactMatch = b.title.toLowerCase() === lowerQuery;

                // If one is exact match and other isn't, exact match comes first
                if (aExactMatch && !bExactMatch) return -1;
                if (!aExactMatch && bExactMatch) return 1;

                // Prioritize songs with cover art
                const aHasCover = !!a.cover;
                const bHasCover = !!b.cover;

                if (aHasCover && !bHasCover) return -1;
                if (!aHasCover && bHasCover) return 1;

                // Otherwise sort by ID (popularity)
                return a.id - b.id;
            });

            resolve(results);
        }, 300); // Faster simulation
    });
};

export const getRandomSuggestions = () => {
    // Return all songs for reference list
    return [...SONG_DATABASE];
};
