// Simulating a database of popular songs with their keys and BPMs
// Expanded to ~100 songs for reference
const SONG_DATABASE = [
    { id: 1, title: "Bohemian Rhapsody", artist: "Queen", key: "Bb Major", bpm: 72, cover: "https://upload.wikimedia.org/wikipedia/en/9/9f/Bohemian_Rhapsody.png", genre: "Rock" },
    { id: 2, title: "Shape of You", artist: "Ed Sheeran", key: "C# Minor", bpm: 96, cover: "https://upload.wikimedia.org/wikipedia/en/b/b4/Shape_Of_You_%28Official_Single_Cover%29.png", genre: "Pop", chords: ['C#', 'F#', 'G#', 'A'] },
    { id: 3, title: "Blinding Lights", artist: "The Weeknd", key: "F Minor", bpm: 171, cover: "https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png", genre: "Pop", chords: ['Fm', 'Eb', 'Bb', 'Dm'] },
    { id: 4, title: "Someone Like You", artist: "Adele", key: "A Major", bpm: 67, cover: "https://upload.wikimedia.org/wikipedia/en/7/7a/Adele_-_Someone_Like_You.png", genre: "Pop", chords: ['A', 'E', 'F#', 'D'] },
    { id: 5, title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", key: "D Minor", bpm: 115, cover: "https://upload.wikimedia.org/wikipedia/en/a/a7/Mark_Ronson_-_Uptown_Funk_%28feat._Bruno_Mars%29_%28Official_Single_Cover%29.png", genre: "Pop" },
    { id: 6, title: "Hotel California", artist: "Eagles", key: "B Minor", bpm: 74, cover: "https://upload.wikimedia.org/wikipedia/en/4/49/Hotelcalifornia.jpg", genre: "Rock" },
    { id: 7, title: "Sweet Child O' Mine", artist: "Guns N' Roses", key: "Db Major", bpm: 125, cover: "https://upload.wikimedia.org/wikipedia/en/6/60/GunsnRosesAppetiteforDestruction.jpg", genre: "Rock", chords: ['D', 'C', 'G', 'A'] },
    { id: 8, title: "Billie Jean", artist: "Michael Jackson", key: "F# Minor", bpm: 117, cover: "https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png", genre: "Pop" },
    { id: 9, title: "Smells Like Teen Spirit", artist: "Nirvana", key: "F Minor", bpm: 116, cover: "https://upload.wikimedia.org/wikipedia/en/3/3c/Smells_Like_Teen_Spirit.jpg", genre: "Rock" },
    { id: 10, title: "Imagine", artist: "John Lennon", key: "C Major", bpm: 76, cover: "https://upload.wikimedia.org/wikipedia/en/6/69/ImagineCover.jpg", genre: "Rock", chords: ['C', 'F', 'Am', 'Dm'] },
    { id: 11, title: "Hallelujah", artist: "Jeff Buckley", key: "C Major", bpm: 48, cover: "https://upload.wikimedia.org/wikipedia/en/7/7e/Jeff_Buckley_-_Grace.jpg", genre: "Rock" },
    { id: 12, title: "Hey Jude", artist: "The Beatles", key: "F Major", bpm: 74, cover: "https://upload.wikimedia.org/wikipedia/en/4/4d/The_Beatles_-_Hey_Jude.jpg", genre: "Rock", chords: ['F', 'C', 'Bb', 'F'] },
    { id: 13, title: "Rolling in the Deep", artist: "Adele", key: "C Minor", bpm: 105, cover: "https://upload.wikimedia.org/wikipedia/en/7/74/Adele_-_Rolling_in_the_Deep.png", genre: "Pop", chords: ['C', 'Gm', 'Bb', 'F'] },
    { id: 14, title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", key: "B Minor", bpm: 89, cover: "https://upload.wikimedia.org/wikipedia/en/c/c8/Luis_Fonsi_Feat._Daddy_Yankee_-_Despacito_%28Official_Single_Cover%29.png", genre: "Pop" },
    { id: 15, title: "Levitating", artist: "Dua Lipa", key: "B Minor", bpm: 103, cover: "https://upload.wikimedia.org/wikipedia/en/f/f5/Dua_Lipa_-_Levitating.png", genre: "Pop" },
    { id: 16, title: "Stay", artist: "The Kid LAROI & Justin Bieber", key: "C# Major", bpm: 170, cover: "https://upload.wikimedia.org/wikipedia/en/0/0c/The_Kid_Laroi_and_Justin_Bieber_-_Stay.png", genre: "Pop" },
    { id: 17, title: "As It Was", artist: "Harry Styles", key: "A Minor", bpm: 174, cover: "https://upload.wikimedia.org/wikipedia/en/b/b1/Harry_Styles_-_As_It_Was.png", genre: "Pop", chords: ['Am', 'F', 'C', 'G'] },
    { id: 18, title: "Flowers", artist: "Miley Cyrus", key: "A Minor", bpm: 118, cover: "https://upload.wikimedia.org/wikipedia/en/a/a3/Miley_Cyrus_-_Flowers.png", genre: "Pop" },
    { id: 19, title: "Drivers License", artist: "Olivia Rodrigo", key: "Bb Major", bpm: 144, cover: "https://upload.wikimedia.org/wikipedia/en/0/09/Olivia_Rodrigo_-_Drivers_License.png", genre: "Pop" },
    { id: 20, title: "Bad Guy", artist: "Billie Eilish", key: "G Minor", bpm: 135, cover: "https://upload.wikimedia.org/wikipedia/en/3/33/Billie_Eilish_-_Bad_Guy.png", genre: "Pop" },
    { id: 21, title: "Watermelon Sugar", artist: "Harry Styles", key: "D Minor", bpm: 95, cover: "https://upload.wikimedia.org/wikipedia/en/b/b1/Harry_Styles_-_Fine_Line.png", genre: "Pop" },
    { id: 22, title: "Don't Start Now", artist: "Dua Lipa", key: "B Minor", bpm: 124, cover: "https://upload.wikimedia.org/wikipedia/en/1/1c/Dua_Lipa_-_Don%27t_Start_Now.png", genre: "Pop" },
    { id: 23, title: "Save Your Tears", artist: "The Weeknd", key: "C Major", bpm: 118, cover: "https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png", genre: "Pop" },
    { id: 24, title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", key: "G# Minor", bpm: 179, cover: "https://upload.wikimedia.org/wikipedia/en/6/63/Lil_Nas_X_-_Montero_%28Call_Me_by_Your_Name%29.png", genre: "Hip-Hop" },
    { id: 25, title: "Peaches", artist: "Justin Bieber", key: "C Major", bpm: 90, cover: "https://upload.wikimedia.org/wikipedia/en/0/00/Justin_Bieber_-_Justice.png", genre: "Pop" },
    { id: 26, title: "Good 4 U", artist: "Olivia Rodrigo", key: "F# Minor", bpm: 167, cover: "https://upload.wikimedia.org/wikipedia/en/6/69/Olivia_Rodrigo_-_Sour.png", genre: "Pop" },
    { id: 27, title: "Kiss Me More", artist: "Doja Cat ft. SZA", key: "G# Major", bpm: 111, cover: "https://upload.wikimedia.org/wikipedia/en/8/87/Doja_Cat_-_Kiss_Me_More.png", genre: "R&B" },
    { id: 28, title: "Industry Baby", artist: "Lil Nas X", key: "D# Minor", bpm: 150, cover: "https://upload.wikimedia.org/wikipedia/en/6/63/Lil_Nas_X_-_Montero_%28Call_Me_by_Your_Name%29.png", genre: "Hip-Hop" },
    { id: 29, title: "Heat Waves", artist: "Glass Animals", key: "B Major", bpm: 81, cover: "https://upload.wikimedia.org/wikipedia/en/b/b0/Glass_Animals_-_Dreamland.png", genre: "Pop" },
    { id: 30, title: "Shivers", artist: "Ed Sheeran", key: "D Major", bpm: 141, cover: "https://upload.wikimedia.org/wikipedia/en/4/4e/Ed_Sheeran_-_Equals.png", genre: "Pop" },
    { id: 31, title: "Cold Heart", artist: "Elton John & Dua Lipa", key: "C# Minor", bpm: 116, genre: "Pop" },
    { id: 32, title: "Easy On Me", artist: "Adele", key: "F Major", bpm: 142, genre: "Pop" },
    { id: 33, title: "ABCDEFU", artist: "GAYLE", key: "E Major", bpm: 122, genre: "Pop" },
    { id: 34, title: "Ghost", artist: "Justin Bieber", key: "B Minor", bpm: 154, genre: "Pop" },
    { id: 35, title: "Enemy", artist: "Imagine Dragons", key: "B Minor", bpm: 77, genre: "Rock" },
    { id: 36, title: "Running Up That Hill", artist: "Kate Bush", key: "C Minor", bpm: 108, genre: "Pop" },
    { id: 37, title: "Anti-Hero", artist: "Taylor Swift", key: "B Major", bpm: 97, genre: "Pop" },
    { id: 38, title: "Unholy", artist: "Sam Smith & Kim Petras", key: "C# Major", bpm: 131, genre: "Pop" },
    { id: 39, title: "Kill Bill", artist: "SZA", key: "Bb Major", bpm: 89, genre: "R&B" },
    { id: 40, title: "Creepin'", artist: "Metro Boomin", key: "C# Minor", bpm: 98, genre: "Hip-Hop" },
    { id: 96, title: "Since U Been Gone", artist: "Kelly Clarkson", key: "G Major", bpm: 131, genre: "Pop" },
    { id: 97, title: "Shake It Off", artist: "Taylor Swift", key: "G Major", bpm: 160, genre: "Pop" },
    { id: 98, title: "Crazy", artist: "Gnarls Barkley", key: "C Minor", bpm: 112 },
    { id: 99, title: "Promiscuous", artist: "Nelly Furtado", key: "Bb Minor", bpm: 114 },
    { id: 100, title: "SexyBack", artist: "Justin Timberlake", key: "C Major", bpm: 117 },
    { id: 101, title: "Don't Stop Believin'", artist: "Journey", key: "E Major", bpm: 119 },
    { id: 102, title: "Livin' on a Prayer", artist: "Bon Jovi", key: "E Minor", bpm: 123 },
    { id: 103, title: "Africa", artist: "Toto", key: "A Major", bpm: 93 },
    { id: 104, title: "Take on Me", artist: "a-ha", key: "A Major", bpm: 169 },
    { id: 105, title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", key: "C Minor", bpm: 125 },
    { id: 106, title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", key: "F# Major", bpm: 120 },
    { id: 107, title: "I Will Survive", artist: "Gloria Gaynor", key: "A Minor", bpm: 116 },
    { id: 108, title: "Eye of the Tiger", artist: "Survivor", key: "C Minor", bpm: 109 },
    { id: 109, title: "Beat It", artist: "Michael Jackson", key: "Eb Minor", bpm: 139 },
    { id: 110, title: "Under Pressure", artist: "Queen & David Bowie", key: "D Major", bpm: 113 },
    { id: 111, title: "Another One Bites the Dust", artist: "Queen", key: "E Minor", bpm: 110 },
    { id: 112, title: "We Will Rock You", artist: "Queen", key: "E Minor", bpm: 81 },
    { id: 113, title: "Summer of '69", artist: "Bryan Adams", key: "D Major", bpm: 139 },
    { id: 114, title: "Jump", artist: "Van Halen", key: "C Major", bpm: 130 },
    { id: 115, title: "Pour Some Sugar on Me", artist: "Def Leppard", key: "C# Minor", bpm: 85 },
    { id: 116, title: "Welcome to the Jungle", artist: "Guns N' Roses", key: "Eb Minor", bpm: 123 },
    { id: 117, title: "Paradise City", artist: "Guns N' Roses", key: "G Major", bpm: 100 },
    { id: 118, title: "November Rain", artist: "Guns N' Roses", key: "B Major", bpm: 79 },
    { id: 119, title: "Enter Sandman", artist: "Metallica", key: "F# Minor", bpm: 123 },
    { id: 120, title: "Nothing Else Matters", artist: "Metallica", key: "E Minor", bpm: 142 },
    { id: 121, title: "Wonderwall", artist: "Oasis", key: "F# Minor", bpm: 87 },
    { id: 122, title: "Don't Look Back in Anger", artist: "Oasis", key: "C Major", bpm: 163 },
    { id: 123, title: "Bitter Sweet Symphony", artist: "The Verve", key: "E Major", bpm: 84 },
    { id: 124, title: "Creep", artist: "Radiohead", key: "G Major", bpm: 92 },
    { id: 125, title: "No Surprises", artist: "Radiohead", key: "F Major", bpm: 76 },
    { id: 126, title: "Karma Police", artist: "Radiohead", key: "A Minor", bpm: 75 },
    { id: 127, title: "Californication", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 96 },
    { id: 128, title: "Under the Bridge", artist: "Red Hot Chili Peppers", key: "E Major", bpm: 85 },
    { id: 129, title: "Otherside", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 123 },
    { id: 130, title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", key: "G# Minor", bpm: 105 },
    { id: 131, title: "Can't Stop", artist: "Red Hot Chili Peppers", key: "E Minor", bpm: 91 },
    { id: 132, title: "Dani California", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 96 },
    { id: 133, title: "By the Way", artist: "Red Hot Chili Peppers", key: "F Major", bpm: 122 },
    { id: 134, title: "Scar Tissue", artist: "Red Hot Chili Peppers", key: "F Major", bpm: 89 },
    { id: 135, title: "Give It Away", artist: "Red Hot Chili Peppers", key: "A Minor", bpm: 92 },
    { id: 136, title: "Every Breath You Take", artist: "The Police", key: "Ab Major", bpm: 117 },
    { id: 137, title: "Roxanne", artist: "The Police", key: "G Minor", bpm: 134 },
    { id: 138, title: "Message in a Bottle", artist: "The Police", key: "C# Minor", bpm: 150 },
    { id: 139, title: "Die With a Smile", artist: "Lady Gaga & Bruno Mars", key: "F Major", bpm: 124 },
    { id: 140, title: "Espresso", artist: "Sabrina Carpenter", key: "F# Minor", bpm: 104 },
    { id: 141, title: "A Bar Song (Tipsy)", artist: "Shaboozey", key: "A Major", bpm: 140 },
    { id: 142, title: "Beautiful Things", artist: "Benson Boone", key: "Eb Major", bpm: 120 },
    { id: 143, title: "Cruel Summer", artist: "Taylor Swift", key: "A Major", bpm: 170 },
    { id: 144, title: "Paint The Town Red", artist: "Doja Cat", key: "Eb Minor", bpm: 110 },
    { id: 145, title: "Lovin On Me", artist: "Jack Harlow", key: "F# Minor", bpm: 83 },
    { id: 146, title: "Agora Hills", artist: "Doja Cat", key: "Bb Major", bpm: 140 },
    { id: 147, title: "What Was I Made For?", artist: "Billie Eilish", key: "C Major", bpm: 104 },
    { id: 148, title: "Vampire", artist: "Olivia Rodrigo", key: "F Major", bpm: 134 },
    { id: 149, title: "Snooze", artist: "SZA", key: "C# Minor", bpm: 102 },
    { id: 150, title: "Daylight", artist: "David Kushner", key: "G Minor", bpm: 80 },
    { id: 151, title: "Please Please Please", artist: "Sabrina Carpenter", key: "C# Minor", bpm: 106 },
    { id: 152, title: "Taste", artist: "Sabrina Carpenter", key: "A Minor", bpm: 107 },
    { id: 153, title: "Birds of a Feather", artist: "Billie Eilish", key: "Bb Major", bpm: 104 },
    { id: 154, title: "Good Luck, Babe!", artist: "Chappell Roan", key: "C Major", bpm: 119 },
    { id: 155, title: "Too Sweet", artist: "Hozier", key: "G Major", bpm: 142 },
    { id: 156, title: "Fortnight", artist: "Taylor Swift ft. Post Malone", key: "Eb Major", bpm: 109 },
    { id: 157, title: "Not Like Us", artist: "Kendrick Lamar", key: "A Minor", bpm: 98 },
    { id: 158, title: "TEXAS HOLD 'EM", artist: "Beyoncé", key: "Bb Major", bpm: 97 },
    { id: 159, title: "I Had Some Help", artist: "Post Malone ft. Morgan Wallen", key: "A Major", bpm: 80 },
    { id: 160, title: "Stick Season", artist: "Noah Kahan", key: "C Major", bpm: 142 },
    { id: 161, title: "Dial Drunk", artist: "Noah Kahan", key: "F Major", bpm: 94 },
    { id: 162, title: "Lose Control", artist: "Teddy Swims", key: "F# Minor", bpm: 140 },
    { id: 163, title: "I Remember Everything", artist: "Zach Bryan ft. Kacey Musgraves", key: "D Major", bpm: 138 },
    { id: 164, title: "Greedy", artist: "Tate McRae", key: "C# Minor", bpm: 122 },
    { id: 165, title: "Exes", artist: "Tate McRae", key: "A Minor", bpm: 108 },
    { id: 166, title: "you're gonna go far", artist: "Noah Kahan", key: "G Major", bpm: 116 },
    { id: 167, title: "Paint the Town Red", artist: "Doja Cat", key: "Eb Minor", bpm: 110 },
    { id: 168, title: "Strangers", artist: "Kenya Grace", key: "F# Minor", bpm: 128 },
    { id: 169, title: "Karma", artist: "Taylor Swift", key: "E Major", bpm: 90 },
    { id: 170, title: "Lavender Haze", artist: "Taylor Swift", key: "F# Major", bpm: 97 },
    { id: 171, title: "Nonsense", artist: "Sabrina Carpenter", key: "Eb Major", bpm: 120 },
    { id: 172, title: "Feather", artist: "Sabrina Carpenter", key: "C# Minor", bpm: 102 },
    { id: 173, title: "Lover", artist: "Taylor Swift", key: "C Major", bpm: 68 },
    { id: 174, title: "Cardigan", artist: "Taylor Swift", key: "Eb Major", bpm: 130 },
    { id: 175, title: "Willow", artist: "Taylor Swift", key: "F Major", bpm: 100 },
    { id: 176, title: "august", artist: "Taylor Swift", key: "Bb Major", bpm: 88 },
    { id: 177, title: "The 1", artist: "Taylor Swift", key: "G Major", bpm: 84 },
    { id: 178, title: "exile", artist: "Taylor Swift ft. Bon Iver", key: "Bb Major", bpm: 94 },
    { id: 179, title: "my tears ricochet", artist: "Taylor Swift", key: "Ab Major", bpm: 102 },
    { id: 180, title: "mirrorball", artist: "Taylor Swift", key: "Bb Major", bpm: 109 },
    { id: 181, title: "betty", artist: "Taylor Swift", key: "Ab Major", bpm: 97 },
    { id: 182, title: "peace", artist: "Taylor Swift", key: "Eb Major", bpm: 90 },
    { id: 183, title: "hoax", artist: "Taylor Swift", key: "Ab Major", bpm: 76 },
    { id: 184, title: "Carolina", artist: "Taylor Swift", key: "G Major", bpm: 128 },
    { id: 185, title: "Snow On The Beach", artist: "Taylor Swift ft. Lana Del Rey", key: "Eb Major", bpm: 101 },
    { id: 186, title: "Bejeweled", artist: "Taylor Swift", key: "C Major", bpm: 105 },
    { id: 187, title: "Mastermind", artist: "Taylor Swift", key: "F# Major", bpm: 106 },
    { id: 188, title: "Vigilante Shit", artist: "Taylor Swift", key: "C Minor", bpm: 90 },
    { id: 189, title: "Labyrinth", artist: "Taylor Swift", key: "Bb Major", bpm: 86 },
    { id: 190, title: "Sweet Nothing", artist: "Taylor Swift", key: "C Major", bpm: 105 },
    { id: 191, title: "Maroon", artist: "Taylor Swift", key: "C Major", bpm: 83 },
    { id: 192, title: "Question...?", artist: "Taylor Swift", key: "A Major", bpm: 99 },
    { id: 193, title: "Midnight Rain", artist: "Taylor Swift", key: "Db Major", bpm: 90 },
    { id: 194, title: "You're On Your Own, Kid", artist: "Taylor Swift", key: "A Major", bpm: 107 },
    { id: 195, title: "Is It Over Now?", artist: "Taylor Swift", key: "A Major", bpm: 137 },
    { id: 196, title: "Now That We Don't Talk", artist: "Taylor Swift", key: "F# Major", bpm: 102 },
    { id: 197, title: "Suburban Legends", artist: "Taylor Swift", key: "D Major", bpm: 107 },
    { id: 198, title: "Slut!", artist: "Taylor Swift", key: "Gb Major", bpm: 88 },
    { id: 199, title: "Say Don't Go", artist: "Taylor Swift", key: "C Major", bpm: 124 },
    { id: 200, title: "Timeless", artist: "Taylor Swift", key: "D Major", bpm: 100 },

    // K-POP SECTION - Top 100 K-pop Songs
    { id: 201, title: "Dynamite", artist: "BTS", key: "C# Minor", bpm: 114, genre: "K-pop" },
    { id: 202, title: "Butter", artist: "BTS", key: "A Major", bpm: 110, genre: "K-pop" },
    { id: 203, title: "Permission to Dance", artist: "BTS", key: "C# Major", bpm: 125, genre: "K-pop" },
    { id: 204, title: "Boy With Luv", artist: "BTS ft. Halsey", key: "E Major", bpm: 120, genre: "K-pop" },
    { id: 205, title: "DNA", artist: "BTS", key: "Eb Minor", bpm: 130, genre: "K-pop" },
    { id: 206, title: "IDOL", artist: "BTS", key: "F# Minor", bpm: 150, genre: "K-pop" },
    { id: 207, title: "MIC Drop", artist: "BTS", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 208, title: "Fake Love", artist: "BTS", key: "C# Minor", bpm: 140, genre: "K-pop" },
    { id: 209, title: "Blood Sweat & Tears", artist: "BTS", key: "D Minor", bpm: 120, genre: "K-pop" },
    { id: 210, title: "Spring Day", artist: "BTS", key: "Ab Major", bpm: 120, genre: "K-pop" },
    { id: 211, title: "Life Goes On", artist: "BTS", key: "Eb Major", bpm: 72, genre: "K-pop" },
    { id: 212, title: "ON", artist: "BTS", key: "C Minor", bpm: 144, genre: "K-pop" },
    { id: 213, title: "Black Swan", artist: "BTS", key: "E Minor", bpm: 104, genre: "K-pop" },
    { id: 214, title: "Yet To Come", artist: "BTS", key: "F Major", bpm: 92, genre: "K-pop" },
    { id: 215, title: "Run BTS", artist: "BTS", key: "G Minor", bpm: 130, genre: "K-pop" },

    { id: 216, title: "DDU-DU DDU-DU", artist: "BLACKPINK", key: "G Minor", bpm: 145, genre: "K-pop" },
    { id: 217, title: "Kill This Love", artist: "BLACKPINK", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 218, title: "How You Like That", artist: "BLACKPINK", key: "D Minor", bpm: 132, genre: "K-pop" },
    { id: 219, title: "Pink Venom", artist: "BLACKPINK", key: "F# Minor", bpm: 90, genre: "K-pop" },
    { id: 220, title: "Shut Down", artist: "BLACKPINK", key: "F Minor", bpm: 125, genre: "K-pop" },
    { id: 221, title: "BOOMBAYAH", artist: "BLACKPINK", key: "Bb Minor", bpm: 130, genre: "K-pop" },
    { id: 222, title: "As If It's Your Last", artist: "BLACKPINK", key: "F# Minor", bpm: 132, genre: "K-pop" },
    { id: 223, title: "Lovesick Girls", artist: "BLACKPINK", key: "Bb Minor", bpm: 130, genre: "K-pop" },
    { id: 224, title: "Playing With Fire", artist: "BLACKPINK", key: "F# Minor", bpm: 120, genre: "K-pop" },
    { id: 225, title: "Forever Young", artist: "BLACKPINK", key: "C# Minor", bpm: 132, genre: "K-pop" },

    { id: 226, title: "OMG", artist: "NewJeans", key: "F# Minor", bpm: 125, genre: "K-pop" },
    { id: 227, title: "Ditto", artist: "NewJeans", key: "A Major", bpm: 120, genre: "K-pop" },
    { id: 228, title: "Attention", artist: "NewJeans", key: "C# Minor", bpm: 125, genre: "K-pop" },
    { id: 229, title: "Hype Boy", artist: "NewJeans", key: "Bb Minor", bpm: 122, genre: "K-pop" },
    { id: 230, title: "Super Shy", artist: "NewJeans", key: "F Major", bpm: 125, genre: "K-pop" },
    { id: 231, title: "ETA", artist: "NewJeans", key: "E Minor", bpm: 138, genre: "K-pop" },
    { id: 232, title: "Cool With You", artist: "NewJeans", key: "G Major", bpm: 115, genre: "K-pop" },

    { id: 233, title: "God's Menu", artist: "Stray Kids", key: "F Minor", bpm: 180, genre: "K-pop" },
    { id: 234, title: "MANIAC", artist: "Stray Kids", key: "G Minor", bpm: 140, genre: "K-pop" },
    { id: 235, title: "Back Door", artist: "Stray Kids", key: "Eb Minor", bpm: 140, genre: "K-pop" },
    { id: 236, title: "Thunderous", artist: "Stray Kids", key: "F# Minor", bpm: 150, genre: "K-pop" },
    { id: 237, title: "S-Class", artist: "Stray Kids", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 238, title: "LALALALA", artist: "Stray Kids", key: "F Minor", bpm: 145, genre: "K-pop" },
    { id: 239, title: "Case 143", artist: "Stray Kids", key: "C# Minor", bpm: 138, genre: "K-pop" },

    { id: 240, title: "FANCY", artist: "TWICE", key: "C# Minor", bpm: 132, genre: "K-pop" },
    { id: 241, title: "Feel Special", artist: "TWICE", key: "Bb Minor", bpm: 120, genre: "K-pop" },
    { id: 242, title: "TT", artist: "TWICE", key: "C# Minor", bpm: 120, genre: "K-pop" },
    { id: 243, title: "Cheer Up", artist: "TWICE", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 244, title: "What is Love?", artist: "TWICE", key: "Eb Minor", bpm: 128, genre: "K-pop" },
    { id: 245, title: "I CAN'T STOP ME", artist: "TWICE", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 246, title: "Alcohol-Free", artist: "TWICE", key: "G Major", bpm: 120, genre: "K-pop" },
    { id: 247, title: "The Feels", artist: "TWICE", key: "F# Major", bpm: 120, genre: "K-pop" },
    { id: 248, title: "Talk that Talk", artist: "TWICE", key: "Bb Minor", bpm: 125, genre: "K-pop" },
    { id: 249, title: "SET ME FREE", artist: "TWICE", key: "D Minor", bpm: 130, genre: "K-pop" },

    { id: 250, title: "Cupid", artist: "FIFTY FIFTY", key: "F# Major", bpm: 125, genre: "K-pop" },
    { id: 251, title: "Perfect Night", artist: "LE SSERAFIM", key: "C# Minor", bpm: 128, genre: "K-pop" },
    { id: 252, title: "ANTIFRAGILE", artist: "LE SSERAFIM", key: "F Minor", bpm: 125, genre: "K-pop" },
    { id: 253, title: "UNFORGIVEN", artist: "LE SSERAFIM", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 254, title: "Eve, Psyche & The Bluebeard's wife", artist: "LE SSERAFIM", key: "Bb Minor", bpm: 135, genre: "K-pop" },

    { id: 255, title: "Queencard", artist: "(G)I-DLE", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 256, title: "Tomboy", artist: "(G)I-DLE", key: "E Minor", bpm: 130, genre: "K-pop" },
    { id: 257, title: "Nxde", artist: "(G)I-DLE", key: "G Minor", bpm: 125, genre: "K-pop" },
    { id: 258, title: "LATATA", artist: "(G)I-DLE", key: "F# Minor", bpm: 120, genre: "K-pop" },
    { id: 259, title: "Oh my god", artist: "(G)I-DLE", key: "D Minor", bpm: 128, genre: "K-pop" },

    { id: 260, title: "Psycho", artist: "Red Velvet", key: "Bb Minor", bpm: 138, genre: "K-pop" },
    { id: 261, title: "Bad Boy", artist: "Red Velvet", key: "F# Minor", bpm: 92, genre: "K-pop" },
    { id: 262, title: "Red Flavor", artist: "Red Velvet", key: "Bb Major", bpm: 120, genre: "K-pop" },
    { id: 263, title: "Peek-A-Boo", artist: "Red Velvet", key: "F Minor", bpm: 120, genre: "K-pop" },
    { id: 264, title: "Russian Roulette", artist: "Red Velvet", key: "Eb Major", bpm: 132, genre: "K-pop" },
    { id: 265, title: "Feel My Rhythm", artist: "Red Velvet", key: "C Major", bpm: 120, genre: "K-pop" },

    { id: 266, title: "Love Dive", artist: "IVE", key: "F# Minor", bpm: 125, genre: "K-pop" },
    { id: 267, title: "After LIKE", artist: "IVE", key: "C# Minor", bpm: 128, genre: "K-pop" },
    { id: 268, title: "ELEVEN", artist: "IVE", key: "Bb Minor", bpm: 125, genre: "K-pop" },
    { id: 269, title: "Kitsch", artist: "IVE", key: "G Minor", bpm: 130, genre: "K-pop" },
    { id: 270, title: "I AM", artist: "IVE", key: "F Minor", bpm: 128, genre: "K-pop" },

    { id: 271, title: "Magnetic", artist: "ILLIT", key: "E Major", bpm: 122, genre: "K-pop" },
    { id: 272, title: "Supernova", artist: "aespa", key: "F# Minor", bpm: 128, genre: "K-pop" },
    { id: 273, title: "Next Level", artist: "aespa", key: "F# Minor", bpm: 130, genre: "K-pop" },
    { id: 274, title: "Savage", artist: "aespa", key: "G Minor", bpm: 150, genre: "K-pop" },
    { id: 275, title: "Black Mamba", artist: "aespa", key: "F# Minor", bpm: 130, genre: "K-pop" },
    { id: 276, title: "Spicy", artist: "aespa", key: "Bb Minor", bpm: 128, genre: "K-pop" },
    { id: 277, title: "Drama", artist: "aespa", key: "E Minor", bpm: 125, genre: "K-pop" },

    { id: 278, title: "Gangnam Style", artist: "PSY", key: "C# Minor", bpm: 132, genre: "K-pop" },
    { id: 279, title: "Gentleman", artist: "PSY", key: "G Minor", bpm: 132, genre: "K-pop" },

    { id: 280, title: "MONEY", artist: "LISA", key: "F# Minor", bpm: 140, genre: "K-pop" },
    { id: 281, title: "LALISA", artist: "LISA", key: "Bb Minor", bpm: 130, genre: "K-pop" },
    { id: 282, title: "On The Ground", artist: "ROSÉ", key: "C# Minor", bpm: 70, genre: "K-pop" },
    { id: 283, title: "SOLO", artist: "JENNIE", key: "G Minor", bpm: 132, genre: "K-pop" },

    { id: 284, title: "Seven", artist: "Jungkook ft. Latto", key: "Bb Major", bpm: 125, genre: "K-pop" },
    { id: 285, title: "3D", artist: "Jungkook ft. Jack Harlow", key: "F# Minor", bpm: 144, genre: "K-pop" },
    { id: 286, title: "Left and Right", artist: "Charlie Puth ft. Jungkook", key: "D Major", bpm: 125, genre: "K-pop" },
    { id: 287, title: "Like Crazy", artist: "Jimin", key: "F# Minor", bpm: 125, genre: "K-pop" },
    { id: 288, title: "Set Me Free Pt.2", artist: "Jimin", key: "G Minor", bpm: 130, genre: "K-pop" },

    { id: 289, title: "Candy", artist: "NCT DREAM", key: "F# Major", bpm: 128, genre: "K-pop" },
    { id: 290, title: "Hot Sauce", artist: "NCT DREAM", key: "Bb Minor", bpm: 128, genre: "K-pop" },
    { id: 291, title: "Kick It", artist: "NCT 127", key: "F Minor", bpm: 130, genre: "K-pop" },
    { id: 292, title: "Sticker", artist: "NCT 127", key: "G Minor", bpm: 128, genre: "K-pop" },

    { id: 293, title: "Growl", artist: "EXO", key: "Bb Minor", bpm: 120, genre: "K-pop" },
    { id: 294, title: "Love Shot", artist: "EXO", key: "F# Minor", bpm: 95, genre: "K-pop" },
    { id: 295, title: "Monster", artist: "EXO", key: "C# Minor", bpm: 105, genre: "K-pop" },
    { id: 296, title: "Call Me Baby", artist: "EXO", key: "G Minor", bpm: 128, genre: "K-pop" },

    { id: 297, title: "Very Nice", artist: "SEVENTEEN", key: "F# Major", bpm: 128, genre: "K-pop" },
    { id: 298, title: "Don't Wanna Cry", artist: "SEVENTEEN", key: "Bb Minor", bpm: 120, genre: "K-pop" },
    { id: 299, title: "Super", artist: "SEVENTEEN", key: "C# Minor", bpm: 130, genre: "K-pop" },
    { id: 300, title: "HOT", artist: "SEVENTEEN", key: "F Minor", bpm: 125, genre: "K-pop" }
];

export const searchSongs = async (query) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            if (!query) {
                resolve([]);
                return;
            }

            const lowerQuery = query.toLowerCase();
            const results = SONG_DATABASE.filter(song =>
                song.title.toLowerCase().includes(lowerQuery) ||
                song.artist.toLowerCase().includes(lowerQuery)
            );
            resolve(results);
        }, 300); // Faster simulation
    });
};

export const getRandomSuggestions = () => {
    // Return all songs for reference list
    return [...SONG_DATABASE];
};
